[Spring Core] 김병준 미션 제출합니다.
next-step/spring-roomescape-playground pull request #141
Opened 2024-03-04 09:28 UTC by byungjunkim3059

안녕하세요, 늦게 제출하여 죄송합니다.

프로그램을 수행했을 때 예약 생성을 하면 생성되지 않습니다. 이 부분 피드백 주시면 감사드리겠습니다.

2024-03-09 14:39 UTC, BGuga requested changes
안녕하세요 병준님 리뷰가 늦었네요 죄송합니다 ㅠㅠ
현재 테스트가 깨지는 이유는
```sql
(
    id      BIGINT       NOT NULL AUTO_INCREMENT,
    name    VARCHAR(255) NOT NULL,
    date    VARCHAR(255) NOT NULL,
    time    VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
}

```

해당 테이블의 time이 time_id로 변경되면서 발생하는 문제입니다.

```sql
CREATE TABLE time
(
    id   BIGINT       NOT NULL AUTO_INCREMENT,
    time VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE reservation
(
    id      BIGINT       NOT NULL AUTO_INCREMENT,
    name    VARCHAR(255) NOT NULL,
    date    VARCHAR(255) NOT NULL,
    time_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (time_id) REFERENCES time(id)
);
```
테이블이 변경됨에 따라 테스트가 깨지는 것입니다!! 미션 진행 9단계 문서를 잘 읽어 보시면 해당 문제에 대한 해결 방법이 적혀있으니 참고하시면 될 것 같습니다 ㅎㅎ

2024-03-09 14:39 UTC, BGuga commented on src/main/java/roomescape/dao/ReservationRowMapper.java
> +}
ReservationRowMapper는 사용 범위가 특정 Dao에 한정될 것 같습니다!
그래서 특정 Dao의 상수로 두는 것이 어떨까요?

2024-03-09 14:39 UTC, BGuga commented on src/main/java/roomescape/dao/TimeDao.java
> +    }
식별자를 통해서 삭제를 한다면 여러 Time이 삭제될 경우는 없을 것 같아요!
그래서 해당 메서드에 두 가지 리뷰를 남기겠습니다!!
1. 네이밍 변경 ( id를 통해 삭제를 한다는 것을 전달할 수 있도록)
2. 적절한 반환값 설정 ( id를 통해 삭제한다면, 꼭 삭제가 되었어야할 경우 예외, 아닐 경우 void로 처리해도 될 것 같습니다)

2024-03-09 14:39 UTC, BGuga commented on src/main/java/roomescape/domain/Reservation.java
> +    }
JsonCreator 를 사용하게된 이유가 무엇일까요??

2024-03-09 14:39 UTC, BGuga commented on src/main/java/roomescape/domain/Reservation.java
> +//    }
주석은 제거해주세요!!

2024-03-09 14:39 UTC, BGuga commented on src/main/java/roomescape/domain/Time.java
> +    }
toString 은 제일 밑에 배치해주세요!!

2024-03-09 14:39 UTC, BGuga commented on src/main/java/roomescape/controller/TimeController.java
> +}
현재 Controller -- Dao 레이어를 가진 시스템을 구성해주셨군요!!
Service 라는 계층을 공부해보시고 적용해보세요!!

2024-03-09 14:39 UTC, BGuga commented on src/main/java/roomescape/controller/TimeController.java
> +    }
현재 Entity인 Time이 그대로 반환되고 있는데 이를 Dto를 반환하도록 변경하고 그 이유를 고민해보시면 좋을 것 같습니다!!

2024-03-10 12:50 UTC, byungjunkim3059 commented
> 안녕하세요 병준님 리뷰가 늦었네요 죄송합니다 ㅠㅠ 현재 테스트가 깨지는 이유는
> 
> ```sql
> (
>     id      BIGINT       NOT NULL AUTO_INCREMENT,
>     name    VARCHAR(255) NOT NULL,
>     date    VARCHAR(255) NOT NULL,
>     time    VARCHAR(255) NOT NULL,
>     PRIMARY KEY (id)
> }
> ```
> 
> 해당 테이블의 time이 time_id로 변경되면서 발생하는 문제입니다.
> 
> ```sql
> CREATE TABLE time
> (
>     id   BIGINT       NOT NULL AUTO_INCREMENT,
>     time VARCHAR(255) NOT NULL,
>     PRIMARY KEY (id)
> );
> 
> CREATE TABLE reservation
> (
>     id      BIGINT       NOT NULL AUTO_INCREMENT,
>     name    VARCHAR(255) NOT NULL,
>     date    VARCHAR(255) NOT NULL,
>     time_id BIGINT,
>     PRIMARY KEY (id),
>     FOREIGN KEY (time_id) REFERENCES time(id)
> );
> ```
> 
> 테이블이 변경됨에 따라 테스트가 깨지는 것입니다!! 미션 진행 9단계 문서를 잘 읽어 보시면 해당 문제에 대한 해결 방법이 적혀있으니 참고하시면 될 것 같습니다 ㅎㅎ

2024-03-10 12:51 UTC, byungjunkim3059 commented
> > 안녕하세요 병준님 리뷰가 늦었네요 죄송합니다 ㅠㅠ 현재 테스트가 깨지는 이유는
> > ```sql
> > (
> >     id      BIGINT       NOT NULL AUTO_INCREMENT,
> >     name    VARCHAR(255) NOT NULL,
> >     date    VARCHAR(255) NOT NULL,
> >     time    VARCHAR(255) NOT NULL,
> >     PRIMARY KEY (id)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 해당 테이블의 time이 time_id로 변경되면서 발생하는 문제입니다.
> > ```sql
> > CREATE TABLE time
> > (
> >     id   BIGINT       NOT NULL AUTO_INCREMENT,
> >     time VARCHAR(255) NOT NULL,
> >     PRIMARY KEY (id)
> > );
> > 
> > CREATE TABLE reservation
> > (
> >     id      BIGINT       NOT NULL AUTO_INCREMENT,
> >     name    VARCHAR(255) NOT NULL,
> >     date    VARCHAR(255) NOT NULL,
> >     time_id BIGINT,
> >     PRIMARY KEY (id),
> >     FOREIGN KEY (time_id) REFERENCES time(id)
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 테이블이 변경됨에 따라 테스트가 깨지는 것입니다!! 미션 진행 9단계 문서를 잘 읽어 보시면 해당 문제에 대한 해결 방법이 적혀있으니 참고하시면 될 것 같습니다 ㅎㅎ

2024-03-10 13:02 UTC, byungjunkim3059 commented
> 안녕하세요 병준님 리뷰가 늦었네요 죄송합니다 ㅠㅠ 현재 테스트가 깨지는 이유는
> 
> ```sql
> (
>     id      BIGINT       NOT NULL AUTO_INCREMENT,
>     name    VARCHAR(255) NOT NULL,
>     date    VARCHAR(255) NOT NULL,
>     time    VARCHAR(255) NOT NULL,
>     PRIMARY KEY (id)
> }
> ```
> 
> 해당 테이블의 time이 time_id로 변경되면서 발생하는 문제입니다.
> 
> ```sql
> CREATE TABLE time
> (
>     id   BIGINT       NOT NULL AUTO_INCREMENT,
>     time VARCHAR(255) NOT NULL,
>     PRIMARY KEY (id)
> );
> 
> CREATE TABLE reservation
> (
>     id      BIGINT       NOT NULL AUTO_INCREMENT,
>     name    VARCHAR(255) NOT NULL,
>     date    VARCHAR(255) NOT NULL,
>     time_id BIGINT,
>     PRIMARY KEY (id),
>     FOREIGN KEY (time_id) REFERENCES time(id)
> );
> ```
> 
> 테이블이 변경됨에 따라 테스트가 깨지는 것입니다!! 미션 진행 9단계 문서를 잘 읽어 보시면 해당 문제에 대한 해결 방법이 적혀있으니 참고하시면 될 것 같습니다 ㅎㅎ

멘토님, 피드백 감사드립니다!

몇 가지 궁금한 점이 있어 질문 드립니다.

위에 말씀하신 time_id를 time으로 고치니 

`SELECT 
    r.id as reservation_id, 
    r.name, 
    r.date, 
    t.id as time_id, 
    t.time as time_value 
FROM reservation as r inner join time as t on r.time_id = t.id`
이 SQL문에서 오류가 나서 다시 time_id로 놓아두었습니다.. 다른 방법이 있으면 피드백 부탁드립니다.

그리고 웹사이트에서 예약을 만들어서 확인을 누르면

> 2024-03-10T22:00:34.713+09:00  WARN 18616 --- [nio-8080-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `roomescape.dto.TimeDTO` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('1')]
이런 에러가 뜹니다..
JSON 데이터를 보니 "time" : "1" 로 오는데 이걸 어떻게 timeDTO로 바꿀지 모르겠습니다. 피드백 부탁드리겠습니다.

감사합니다. 

>

2024-04-06 04:26 UTC, closed without merging