Week2  Spring JDBC 5단계 6단계 7단계
next-step/spring-roomescape-playground pull request #156
Opened 2024-03-26 12:39 UTC by joamksh

Week2  Spring JDBC 5단계 6단계 7단계 완료 했습니다
다만, 코드 정리 및 service class나 repository 등 코드를 좀 더 구조화해서 바꿔야 할 것 같습니다 
현재 상태는 controller에다가 코드가 잔뜩 들어있는 상황인데 이렇게 될 경우 수정에도 용이하지 않고 가독성도 떨어져서 좋은 코드가 아닌 것 같습니다.  아직 스프링의 구조들을 배우고 있지만 이렇게 새로운 문제를 만났을 때 활용하는 것이 좀 부족한 것 같습니다. 이와 관련된 조언이 있다면 주시면 감사하겠습니다.

2024-03-26 12:48 UTC, joamksh reviewed
h2는 다른 기초 책에서 사용한 적이 있는데 항상 제작할 때마다 궁금한 점이 있습니다.
제가 배운방법은 cmd에다가 copy con local.mv.dbvZ로 파일을 제작한후
localhost:8080/h2-console로 들어가서 해당 경로로 연결 버튼을 누르는 것인데 
이 방법이 늘 똑같이 한다고 생각하는데 경우에 따라 제대로 생성이 안 될 때도 있어서
혹시 다른 방법으로 하셨다면 어떤 방버으로 하셨는지 궁금합니다.
저는 이번에는 window에 깔려 있는 h2-console을 이용했습니다.
또한, 저는 지금까지 h2,mariadb로 springboot를 해본 경험이 있는데 이 밖에 다른 DBMS를 사용하신 적이 있으신지 , 있으시다면 이 두 개와 차이점이 있는지가 궁금합니다.!

2024-03-26 12:55 UTC, joamksh reviewed
우선 이 마지막 단계에서 굉장히 많은 시간과 여러 번의 변경이 있었습니다
1. 우선 이 마지막 단계를 수행하기 위한 코드
2. 이번 주차 5,6,7테스트 말고 저번주 테스트가 이번에 바뀐 코드에도 반영되도록 -> 이 부분에서 많은 변경이 있었습니다. 특히 3단계,4단계!! 구글링으로 검색해서 돌아가게 고쳤는데 혹시 어떻게 진행하셨는지 궁금합니다.

2024-03-26 12:55 UTC, joamksh commented on src/main/java/roomescape/ReservationController.java
> -    @GetMapping("/")
view와 관련된 부분은 따로 viewContorller를 만들어서 @Controller와 @RestController를 사용할 수 있도록 변경했습니다.

2024-03-26 12:55 UTC, joamksh commented on src/main/java/roomescape/ReservationController.java
> +                ));
학습 교재를 바탕으로 query문을 사용해서 해당 데이터들을 get할 수 있도록 코드를 짰습니다.

2024-03-26 12:55 UTC, joamksh commented on src/test/java/roomescape/MissionStepTest.java
> +    }
해당 테스트가 전부 잘 돌아가는 것을 확인했습니다.

2024-03-28 06:47 UTC, hafnium1923 requested changes
안녕하세요 수현~! 너무 오래걸렸죠? 흑흑,,, 미리 말씀 못드려서 죄송해요..ㅜㅠㅠ 핑퐁이 더 필요하다면 머지하지 않고 주말에 이어가는 방법도 있으니..!! 제가 드린 질문 확인해보시면 좋을 것 같아요.
먼저 저는 이번 미션을 못했어요🫠 지난주 스터디시간에 말한 것 처럼 과제테스트기간이 겹쳐버려서...ㅠ 그래서 마지막에 물어보신 테스트 통과 방법에 대해 말씀드리기 어려울 것 같아요. 스터디 시간에 다른 스터디원과 함께 고민해보아용~!~ 리뷰는 제안보단 질문이 쫌 더 많습니다!

>  코드 정리 및 service class나 repository 등 코드를 좀 더 구조화해서 바꿔야 할 것 같습니다. 아직 스프링의 구조들을 배우고 있지만 이렇게 새로운 문제를 만났을 때 활용하는 것이 좀 부족한 것 같습니다. 이와 관련된 조언이 있다면 주시면 감사하겠습니다.

저도 언제나 새로운 언어를 배우고 새로운 프레임워크를 배우면 폴더구조, 파일 구조를 어떻게 나눠야할지가 가장 고민이랍니다ㅋㅋ 대중적인건 있어도 다 취향차이라,, 어떻게 딱 말씀드리기가 어렵네요. 저도 스프링을 잘하는 건 아니지만 여러 프레임워크를 배워본 입장으로서 말해보자면, 전 진짜 진심으로 배우고 싶은 프레임워크에선 처음부터 남들이 하란대로 절대 안해요ㅎ 대중적인 건 그 이유가 있을 거라 생각하긴 한데 직접 그 구조가 만들어지게 된 이유를 느껴보고 공감해보고 싶어서요! 제가 하고 싶은대로 구조도 폴더도 나누고 난 뒤, 리뷰를 통해 다른사람의 생각도 들어보면서 지내다 보면 어느새 필요성을 느끼게 되더라구요. 확실히 실력이 늘면 보이는게 많아지니까 왜 그런 구조가 되었는지 이해되는 것 같아요. 수현도 이것저것 해보면서 너무 길면 나눠도보고, 이런저런 구조로 하다보면 본인만의 컨벤션이 잡힐거에요!

> h2는 다른 기초 책에서 사용한 적이 있는데 항상 제작할 때마다 궁금한 점이 있습니다. 이 방법이 늘 똑같이 한다고 생각하는데 경우에 따라 제대로 생성이 안 될 때도 있어서 혹시 다른 방법으로 하셨다면 어떤 방법으로 하셨는지 궁금합니다

일단 제가 질문을 제대로 이해했는지 모르겠지만, 말씀하신 거 토대로 찾아봤어요 (저는 잘 몰라서요😂) H2 데이터베이스는 임베디드 모드와 서버 모드로 운영할 수 있는데 사용하신 방법은 서버 모드를 사용하는 거래요. 생성안되는 경우는 경로설정, 파일권한, H2 버전호환 등 원인이 다양해서 콘솔을 확인해봐야 정확하게 알 수 있다고 하네요! 다른 DBMS를 경험한 적,.? 은 oracle밖에 없긴한데 대충 여러 디비의 장단점을 말해보자면 
PostgreSQL: 확장성과 표준 준수도가 높은 오픈 소스 RDBMS
MySQL: 웹 기반 애플리케이션에 널리 사용
Oracle DB: 대규모 엔터프라이즈 환경에 적합한 강력한 기능을 제공
MongoDB: MongoDB는 스키마가 없는 NoSQL 데이터베이스
라고 하는데 주변 개발자한테 뭐가 젤 핫하고 유용하냐고 물어보니까 핫한건 PostgreSQL인데 걍 필요에 따라 맞춰서 쓰는것도 역량이라고 하네요 ^^;;ㅋㅋㅋ

2024-03-28 06:47 UTC, hafnium1923 commented on src/main/java/roomescape/GlobalExceptionHandler.java
> +    @ExceptionHandler(NotFoundReservationException.class)
NotFoundReservationException 클래스에 대한 예외 처리가 두 번 정의되어 있네요! 동일한 예외에 대해 다른 상태를 반환하고자 한건가요??

2024-03-28 06:47 UTC, hafnium1923 commented on src/main/java/roomescape/GlobalExceptionHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
질문) ResponseEntity를 반환할 때는 HttpStatus를 ResponseEntity 생성자 또는 ResponseEntity 빌더 메소드를 통해 직접 지정할 수 있어서 해당 어노테이션을 필요하지 않는다?고? 봤던 거같은데 사용한 이유가 궁금해요!

2024-03-28 06:47 UTC, hafnium1923 commented on src/main/java/roomescape/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleBadRequestException(NotFoundReservationException ex, WebRequest request) {
얘는 공통적으로 사용되는 예외처리라 이름이 추상적일까요! 아니라면 좀 더 명확하면 좋을 것 같아서요~

2024-03-28 06:47 UTC, hafnium1923 commented on src/main/java/roomescape/Reservation.java
> +            return null;
null을 반환하는 것은 호출하는 쪽에서 예외적인 상황을 처리하기 어렵게 할 수도 있다고도 하네요!

2024-03-28 06:47 UTC, hafnium1923 commented on src/main/java/roomescape/ReservationController.java
> +            throw new NotFoundReservationException("Required fields are missing.");
유효하지 않은 예약데이터와 예약이 존재하지 않을 때 던져지는 예외가 동일한게 뭔가 어색해요! 예약은 존재하는데 데이터가 유효하지 않은 것과 예약 자체가 없는건 좀 다른 류가 아닐까 생각하거든요!

2024-03-28 06:47 UTC, hafnium1923 commented on src/main/java/roomescape/ReservationController.java
> +        // 새로운 예약이 추가되면 바로 해당 예약을 반환합니다.
질문) jdbcInsert.executeAndReturnKey(parameters)를 통해 새 예약의 ID를 얻었으니 입력받은 예약정보를 사용해서 Reservation객체를 직접 생성해 반환하는 방식도 있는데 조회 과정을 진행한 이유가 있다면 궁금해요!

2024-03-29 01:04 UTC, joamksh commented
코드 외적으로 제가 궁금했던 부분에 대해서 친절하게 설명해주셔서 감사합니다! 
다양한 db를 사용해봐야겠다는 생각이 드네요! 
바쁘신 와중에도 자세하게 설명해주시고 제 코드에 대해서도 많이 봐주셔서 덕분에 저도 공부가 많이 된 것 같아요! 감사합니다.

2024-04-01 09:41 UTC, hafnium1923 approved these changes

2024-04-01 10:23 UTC, jaeyeonling approved these changes

2024-04-01 10:23 UTC, merged