[Spring MVC] 아트(김태윤) 미션 제출합니다.
next-step/spring-roomescape-playground pull request #160
Opened 2024-03-28 13:08 UTC by pykido

[Spring MVC] 닉네임(실명) 미션 제출합니다. 각 단계별 풀이를 간단히 남겨봅니다!

### 1단계 : localhost:8080 요청 시 아래 화면과 같이 어드민 메인 페이지가 응답할 수 있도록 구현하기
- controller를 통해 templates/home.html을 view에 띄울 수 있었습니다.
- 단, home.hmtl 파일을 그대로 사용하기에 의존성을 추가하는 과정이 필요했습니다.
  `implementation 'org.springframework.boot:spring-boot-starter-thymeleaf' `

### 2단계 : /reservation 요청 시 예약 관리 페이지가 응답할 수 있도록 구현하고 예약 관리 페이지 로드 시 호출되는 예약 목록 조회 API도 함께 구현하기
- 1단계와 같은 방법으로 예약 관리 페이지가 응답하도록 구현하였습니다.
- API 명세에 따르면 /reservations 요청 시 예약 목록을 응답해야 하므로 예약자 정보가 담긴 클래스를 만든 후 예약 목록 List를 만들어 문제 조건에 맞게 구현하였습니다.

### 3단계 : API 명세를 따라 예약 추가 API 와 삭제 API를 구현하기
## (1) 예약 추가 API 구현
- 예약자 객체를 할당하여 이전에 만들었던 예약 목록 List에 추가해주었습니다.
- 그 후 문제 조건에 맞게  Created 응답, header 정보와 함께 생성된 예약 정보를 body에 넣어 반환해주엇습니다.
## (2) 예약 삭제 API 구현 
- 삭제하려고 하는 예약자의 id값을 에약 목록 List에서 찾아 삭제하도록 구현하였습니다.
- 그 후 문제 조건에 맞게 204 No content 응답을 반환해주었습니다.

### 4단계 : 예약 관련 API 호출 시 에러가 발생하는 경우 중 요청의 문제인 경우 Status Code를 400으로 응답하기
## (1) 예약 추가 시 필요한 인자값이 비어있는 경우
- 조건문을 통해 필요한 인자값이 비어있는 경우 문제 조건에 맞게 Bad request인 status cod 400 응답을 반환하였습니다. 

## (2) 삭제 할 예약의 식별자로 저장된 예약을 찾을 수 없는 경우
-삭제할 id값을 찾지 못한 경우 문제 조건에 맞게 Bad request인 status cod 400 응답을 반환하였습니다. 

# 미션을 하며 생긴 질문 사항이 있습니다!
- 4단계 미션 중 status code 400으로 응답하는 것 뿐만 아니라 Error 메시지까지 응답하도록 구현하고 싶었는데 구현하지 못해 아쉽습니다 ㅠㅠㅠ.....

2024-03-31 05:08 UTC, pykido commented
PR 다시 올립니다!

2024-03-31 05:37 UTC, Kim0914 requested changes
안녕하세요 아트 !
미션 진행하신다고 고생많으셨습니다.

이번 리뷰에는 스프링 사용법과 관련한 몇 가지 질문을 남겼어요.
확인해주시면 감사하겠습니다 ㅎㅎ

2024-03-31 05:37 UTC, Kim0914 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
적절한 의존성을 잘 찾아 추가해주셨네요 👍

2024-03-31 05:37 UTC, Kim0914 commented on src/main/java/roomescape/ReservationController.java
> +@RestController
RestController 어노테이션을 잘 선언해주셨네요 !
`@Controller`와 `@RestController `는 어떤 차이가 있었나요 ?

2024-03-31 05:37 UTC, Kim0914 commented on src/main/java/roomescape/ReservationController.java
> +    private AtomicLong index = new AtomicLong(1); // 예약자 번호
AtomicLong을 사용해주신 이유가 궁금합니다 ㅎㅎ

2024-03-31 05:37 UTC, Kim0914 commented on src/main/java/roomescape/ReservationController.java
> +    private List<Reservation> reservations = new ArrayList<>(); // 예약 정보들이 들어있는 리스트
꼼꼼하게 주석까지 잘 달아주셨네요..👍

실제 협업을 할 때는 주석대신 변수명과 메서드 명으로 의미를 확실하게 나타내고는 합니다.

정말 복잡한 로직에는 주석을 사용해도 좋지만, 되도록 주석을 사용하지 않는 것이 일반적인 컨벤션입니다 😎

2024-03-31 05:37 UTC, Kim0914 commented on src/main/java/roomescape/ReservationController.java
> +            return ResponseEntity.badRequest().build();
> 4단계 미션 중 status code 400으로 응답하는 것 뿐만 아니라 Error 메시지까지 응답하도록 구현하고 싶었는데 구현하지 못해 아쉽습니다 ㅠㅠㅠ.....

질문에 대한 답변 드릴게요.

ResponseEntity의 .body() 메서드를 체이닝해서 메시지를 설정할 수 있습니다 !

추가적으로 4단계 키워드 중 `@ExceptionHandler`와 `@ControllerAdvice`가 있습니다. 이 2가지 어노테이션을 학습하고 적용해보신다면 예외 처리에 대한 큰 흐름을 파악하실 수 있을거에요.

2024-03-31 05:37 UTC, Kim0914 commented on src/main/java/roomescape/ReservationController.java
> +        return ResponseEntity.status(HttpStatus.CREATED)
CREATED의 경우 왜 Location을 같이 응답할까요?!
의견 남겨주세요 !

2024-03-31 05:37 UTC, Kim0914 commented on src/main/java/roomescape/PageController.java
> +        return "home";
"templates"은 경로로 표시하지 않아도 되는 이유가 무엇일까요 !

2024-03-31 13:46 UTC, pykido commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
감사합니다! ㅎ

2024-03-31 14:17 UTC, pykido commented on src/main/java/roomescape/ReservationController.java
> +@RestController
@Controller 와 @RestController는 주요 기능에 있어서 큰 차이점이 있습니다. @Controller의 주요 기능은 View를 랜더링하는 ViewResolver의 설정에 맞게 **View를 반환하는 것**입니다.(이때, @Controller는 Model 객체를 만들어 데이터를 담아 View를 반환하기도 합니다) 반면, @RestContorller의 주요 기능은 **Json 형태로 객체 데이터를 반환하는 것**입니다. 추가적으로, @Controller에 @ResponseBody를 추가적으로 어노테이션하면 @RestController처럼 Json 형태로 데이터를 반환할 수 있습니다.

2024-03-31 14:57 UTC, pykido commented on src/main/java/roomescape/ReservationController.java
> +    private AtomicLong index = new AtomicLong(1); // 예약자 번호
⭐️⭐️ **결론부터 말씀 드리자면 AtomicLong은 int, Long과 달리 thread-safe하게 구현되어 멀티쓰레드에서 synchronized보다 적은 비용으로 동시성을 보장할 수 있습니다!** 
 예를 들어 자료형이 Long인 변수값을 증가시키는 계산을 한다면 다음과 같은 3가지 연산이 발생하게 됩니다. 변수의 초기 값을 얻고, 증가시키고, 증가시킨 값을 업데이트합니다. **여러 개의 스레드가 하나의 변수에 대해 연산하게 된다면 연산 과정이 꼬여 정보의 손실이 발생하게 될 수 있습니다.  이러한 문제점을 동시성 문제라고 합니다.** 실제로 스레드들은 프로세스들과 달리 코드 영역과 데이터 영역을 공유하기에 스레드 하나가 잘못된 연산이나 버그 등으로 비정상 종료를 하게 된다면 같은 프로세스에 속한 다른 스레드들까지 강제로 종료됩니다. 이때, synchronized 키워드를 통해 여러 스레드가 한 가지 변수값에 대해 연산할 때 lock을 걸어 한 번에 한 스레드만이 연산 과정을 진행하여 동시성 문제를 해결할 수 있습니다. 그러나 한 번에 한 스레만이 연산 과정을 진행하기에 다른 스레드들은 기다리게 되는, 성능적인 문제점이 발생하게 됩니다. 
 앞선 문제들을 CAS 알고리즘을 통해 해결하였습니다. **CAS 알고리즘 또한 synchronized처럼 한 스레드가 다른 스레드들과의 경합에서 이기고 변수 값을 업데이트합니다. 그러나 synchronized와 달리 한 스레드가 변수 값을 업데이트하는 동안 다른 스레드들은 추가로 다른 작업을 수행할 수 있습니다.** 
 따라서 저는 위와 같은 이유로 예약자 번호와 같이 멀티쓰레드가 발생하기 쉬운 변수값을 AtomicLong을 사용하여 구현하였습니다!

2024-03-31 15:00 UTC, pykido commented on src/main/java/roomescape/ReservationController.java
> +    private List<Reservation> reservations = new ArrayList<>(); // 예약 정보들이 들어있는 리스트
감사합니다! 배우는 입장에서 변수와 메서드 등 무엇이든 제대로 짚고 넘어가야겠다는 생각에 주석을 사용하였습니다! 다시 생각해보니 변수와 메서드 등과 같은 작은 것들에 집중하기보다는 프로젝트의 전체적인 flow를 읽는 것이 더욱 중요하다고 생각됩니다! 그렇기에 주석 사용을 줄이고 전체적인 flow와 기능적인 구현에 집중하는 개발자가 되겠습니다!

2024-03-31 19:37 UTC, pykido commented on src/main/java/roomescape/ReservationController.java
> +        return ResponseEntity.status(HttpStatus.CREATED)
Post 요청에 따른 Created(201) 응답 코드는 요청이 성공적으로 처리되었고 새로운 리소스가 생성되었음을 나타냅니다! 이때, Location을 같이 응답하는 이유는 RESTful API의 설계 원칙 중 하나인 "Post 후 리다이렉션"에 따른 것으로 post 요청에 의해 새로운 리소스가 생성되면 리소스의 위치를 응답해야하기 때문입니다. 이를 통해 클라이언트는 해당 리소스에 대해 접근할 수 있습니다!

2024-03-31 19:39 UTC, pykido commented on src/main/java/roomescape/PageController.java
> +        return "home";
왜냐하면 templates 디렉토리는 일반적으로 Spring 프레임워크에서 View를 저장하는 곳이기에 Controller 작동시 Spring 내부적으로 이 디렉토리에 있는 파일들을 읽어들이기 때문입니다.

2024-04-01 11:56 UTC, pykido commented on src/main/java/roomescape/ReservationController.java
> +            return ResponseEntity.badRequest().build();
말씀해주신 .body() 메서드를 통해 메세지를 설정하였습니다! 다만, 아직 특정 예외 처리에 익숙지 않아 @ExceptionHandler와 @ControllerAdvice는 정확히 구현하지 못했습니다. 구현에 어려움이 있더라도 꼭 완성시키고 싶기에 다음 step을 구현하며 완성시켜보겠습니다!!

2024-04-02 09:16 UTC, Kim0914 approved these changes
달아주신 코멘트 모두 확인했습니다 !

다음 미션에서는 미션의 목적에 더해, 의미를 가지는 부분을 메서드로 분리하는 연습을 함께하면 좋을 것 같아요 :)

다음 단계로 갑시다 ~

2024-04-02 09:16 UTC, Kim0914 commented on src/main/java/roomescape/ReservationController.java
> +        if (Objects.equals(reservation.getName(), "") || Objects.equals(reservation.getDate(), "") || Objects.equals(reservation.getTime(), "")) {
미션의 목적인 스프링 사용법과는 조금 다른 부분이라 참고만 하셔도 좋을 것 같아요 !

예외를 검증하는 부분이나, 의미를 나타내는 식들은 메서드로 분리하는 연습을 해보는건 어떨까요?ㅎㅎ
의미를 분명히 드러낼 수 있고, 중복 로직을 제거할 수 있겠죠?

2024-04-07 09:39 UTC, pykido commented on src/main/java/roomescape/ReservationController.java
> +        if (Objects.equals(reservation.getName(), "") || Objects.equals(reservation.getDate(), "") || Objects.equals(reservation.getTime(), "")) {
설명 감사드립니다! 다음 단계로 넘어가겠습니다~!!!

2024-04-08 02:26 UTC, merged