[Spring JDBC] 김서현 미션 제출합니다
next-step/spring-roomescape-playground pull request #231
Opened 2024-05-15 13:54 UTC by seobbang

Spring MVC 미션 제출합니다.

## 🚀 5단계 - 데이터베이스 적용하기
- [x] gradle 의존성 추가
- [x] 테이블 스키마 정의
- [x] 데이터베이스 설정

## 🚀 6단계 - 데이터 조회하기
- [x] select 쿼리 이용해 데이터 조회하기 구현

## 🚀 7단계 - 데이터 추가/삭제하기
- [x] Insert 쿼리 이용해 예약 추가 구현
- [x] Delete 쿼리 이용해 예약 삭제 구현

`Simplejdbcinsert`객체를 이용해서 코드를 짜보기도 했는데, 이해가 어려워서 좀 더 쉬운 JdbcTemplate의 update를 사용해서 구현했습니다!

DAO(Data Access Object)를 만들어서 쿼리문을 실행하는 코드를 넣었고, 관련해서 공부하다 보니 DAO -> Service -> Controller 로 서비스 흐름이 될 수 있도록 Service도 나누는 것 같더라구요..!

우선 저는 기능들이 많지 않다보니 DAO -> Controller로만 구현했는데, Service까지 분리하는게 좋을까요?

2024-05-16 05:15 UTC, kyY00n requested changes
서현님 수고하셨습니당 :D
코멘트 남겨놨으니 궁금한 점이 있다면 답글달아주세요.

그리고 남겨주신 질문에 대한 작은 요청이 있습니다.

> 우선 저는 기능들이 많지 않다보니 DAO -> Controller로만 구현했는데, Service까지 분리하는게 좋을까요?

**Service 계층이 왜 등장했는지를 찾아주세요.**
그리고 그것의 필요성이 서비스를 추가하는 비용보다 크다고 판단한다면 Service를 적용해보세요 :D

미션 구현에 정답은 없기 때문에 판단의 근거를 말할 수 있으면 된다고 생각해요!
+) 만약 불필요하다고 생각하더라도, 경험삼아 서비스 레이어를 분리해보고 싶다면 적용해볼 수 있지 않을까요?

2024-05-16 05:15 UTC, kyY00n commented on build.gradle
> +    implementation 'com.h2database:h2'
Gradle dependencies의 implementation과 testImplementation의 차이는 무엇인가요?

2024-05-16 05:15 UTC, kyY00n commented on src/main/java/roomescape/ReservationController.java
>  @ControllerAdvice
`@ControllerAdvice` 어노테이션은 스프링의 예외를 전역적으로 관리하고 싶을 때 사용해요. 그 관점에서 클래스명과 위치를 다시 고민해볼까요?

2024-05-16 05:15 UTC, kyY00n commented on src/main/java/roomescape/ReservationController.java
> +//        테스트 코드를 위해 기존 ResponseDto를 이용한 코드 주석 처리
기존에 Dto를 적용했던 이유가 무엇이었나요?
DTO를 사용하는 장점은 무엇일까요?
DTO를 사용하기 위해서 테스트를 수정하는 것은 안될까요?

2024-05-16 05:15 UTC, kyY00n commented on src/main/java/roomescape/ReservationController.java
> +        ReservationRequestDto newReservation = new ReservationRequestDto(name, date, time);
request를 그대로 사용하지 않은 이유가 있나요?

2024-05-16 05:15 UTC, kyY00n commented on src/main/java/roomescape/ReservationController.java
> +        long id = queryingDAO.createReservation(newReservation);
DAO에 Controller에서 사용했던 DTO를 재사용하셨네요!

그런데 만약 API 요청 스펙이 변경되면 DAO의 인자 타입도 변경되겠군요.

계층간 DTO를 사용하는 이유를 조금 더 알아볼까요?

2024-05-16 05:15 UTC, kyY00n commented on src/main/java/roomescape/ReservationQueryingDAO.java
> +    public int deleteReservationById(long id) {
delete~(삭제한다) 라는 메서드의 이름과 달리 반환값을 가지고 있네요.

`jdbcTemplate.update`의 반환값을 그대로 반환하고 있는데, DAO의 사용자 입장에서 직관적일까요?

만약 그렇지 않다면 어떻게 해결할 수 있을까요?
(유일한 답은 없으니 의견을 말해주세요!!)

2024-05-16 05:15 UTC, kyY00n commented on src/main/java/roomescape/ReservationQueryingDAO.java
> +
저는 법은 아니라 생각하는데

보통 상수, static 변수, 인스턴스 변수, 생성자, 메서드 순 으로 선언해요!


참고: https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html

2024-05-16 05:15 UTC, kyY00n commented on src/main/java/roomescape/ReservationRequestDto.java
> +        }
spring boot starter validation 을 적용해볼까요?

참고: https://dev-coco.tistory.com/123

2024-05-16 05:15 UTC, kyY00n commented on src/test/java/roomescape/MissionStepTest.java
> +    void 칠단계() {
테스트 명을 보다 의미있게 지어볼 수 있을까요? 🍀

참고: https://blog.naver.com/genycho/220317775484

2024-05-16 05:15 UTC, kyY00n commented on src/test/java/roomescape/MissionStepTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
줄바꿈이 추가되면 좋을 것 같군요!!
+) 인텔리제이 Reformat code 기능을 사용해보시겠어요?

2024-05-22 05:55 UTC, seobbang commented on build.gradle
> +    implementation 'com.h2database:h2'
> `implementation` : 기본적인 의존성 설정으로 프로덕션 코드를 작성할 때 필요한 라이브러리를 지정한다. 컴파일, 런타임시 모두 사용된다.
> 
> `testImplementation` : 테스트 코드를 작성할 때 필요한 라이브러리를 지정한다. 테스트 소스 세트에서만 사용되며, 프로덕션 코드에는 포함되지 않는다.

2024-05-22 05:59 UTC, seobbang commented on src/main/java/roomescape/ReservationController.java
> +//        테스트 코드를 위해 기존 ResponseDto를 이용한 코드 주석 처리
response 형식 {code, message, data}의 형식이 반복되어 이를 dto로 사용하고자 했어요!
`DTO를 사용하는 장점`은 캡슐화와 유지보수성, 보안성 입니다.

DTO를 사용하기 위해 테스트를 수정하는 것도 괜찮지 않을까 하는 의견입니다..! 그렇다면 혹시 테스트를 수정해도 되는건가요 ..?!

2024-05-22 06:05 UTC, seobbang commented on src/main/java/roomescape/ReservationController.java
> +        ReservationRequestDto newReservation = new ReservationRequestDto(name, date, time);
createReservation에서 `ReservationRequestDto` 데이터를 인자로 받도록 구현해서, 그곳에 전달하고자 객체를 하나 생성해주었습니다! 

생각해보니 createReservation에서 어차피 각각의 데이터를 다시 get하여 쓰고 있으니 굳이 requestDto로 한번 거쳐서 받을 필요 없다는 생각이 드네요!

그럼
```
 public long createReservation(ReservationRequestDto reservation) {
```
여기서 그냥 각 value를 받는식으로 리팩토링하는게 좋을까요?

2024-05-22 06:07 UTC, seobbang commented on src/main/java/roomescape/ReservationQueryingDAO.java
> +    public int deleteReservationById(long id) {
```
public int deleteReservationById(long id) {
        String sql = "DELETE FROM reservation WHERE id = ?";
        return jdbcTemplate.update(sql, id);
    }
```

이 코드를
```
public int deleteReservationById(long id) {
        String sql = "DELETE FROM reservation WHERE id = ?";
        int deletedId = jdbcTemplate.update(sql, id);
        return deltedId;
    }
```

이런식으로 변경하는건 어떨까요?!

2024-05-22 06:10 UTC, seobbang commented on src/test/java/roomescape/MissionStepTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
Window: `Ctrl + Alt + L`

2024-05-22 06:21 UTC, seobbang commented on src/test/java/roomescape/MissionStepTest.java
> +    void 칠단계() {
오단계, 육단계, 칠단계만 변경해봤습니다..! 이게 맞는건지 모르겠네요 😂

2024-05-22 06:25 UTC, seobbang commented on src/main/java/roomescape/ReservationController.java
> +        long id = queryingDAO.createReservation(newReservation);
DTO는 계층간 데이터 전송을 최적화하기 위한 추상화의 목적이라고 이해했는데, 그럼 API 스펙이 변경되었을 때 DTO가 바뀔 수는 없으니, DAO Controller에서는 DTO를 사용하지 않고  위에서 말한 맥락에 이어서 그냥 인자로 request를 그대로 받는 것이 좋은걸까요?! 제가 잘 이해한건지 모르겠네요..!.!>!

2024-05-22 06:28 UTC, seobbang commented on src/main/java/roomescape/ReservationController.java
>  @ControllerAdvice
`@ControllerAdvice`없이 `ReservationController` 안에 지역적으로 쓸까 고민하다가, 제가 짜놓은 ExceptionHandler를 보니 충분히 전역적으로 쓰일 수 있겠다는 생각이 들어서 다른 class로 아예 빼주고, CommonExceptionHandler라는 이름을 사용해봤습니다! 통상적으로는 어떤 이름을 많이 쓰나요!?

2024-05-22 15:02 UTC, kyY00n commented on src/main/java/roomescape/ReservationController.java
>  @ControllerAdvice
전 좋은데요? 만약 함께 기여하는 사람들이 있다면 그 구성원들 간에 이해하는 언어라면 무엇이든 괜찮다고 생각합니다.
전역이라는 의미를 강조하기 위해 Global 같은 말을 써볼 수도 있을 것 같습니다.

2024-05-22 15:06 UTC, kyY00n commented on src/main/java/roomescape/ReservationController.java
> +//        테스트 코드를 위해 기존 ResponseDto를 이용한 코드 주석 처리
네. 왜냐면 그러지 말라는 말이 없으니까요 🗡️
만약 안 되는 일이었다 해도 더 나은 코드를 위해 필요하다면 건의해볼 수 있는 일입니다!!

미션이 아니라 보통의 협업이었다면 테스트코드도 유지보수의 대상이기 때문에 필요하다면 당연히 수정했을 것 같습니다.

2024-05-22 15:06 UTC, kyY00n commented on src/main/java/roomescape/ReservationController.java
> +        ReservationRequestDto newReservation = new ReservationRequestDto(name, date, time);
네 상관없을 것 같습니다 :D

2024-05-22 15:18 UTC, kyY00n commented on src/main/java/roomescape/ReservationQueryingDAO.java
> +    public int deleteReservationById(long id) {
변수 선언하고 바로 반환하는 형식이라, 큰 차이는 없는 것 같아요.
제가 말한 내용은 `삭제하다` 라는 메서드가 삭제만 하고 끝나는 게 아니라 어떤 값을 반환하고 있는 실제 구현에 대해 말한 것이었어요.

클린코드 - 명령과 조회를 분리하라 부분을 참고해 이해해보면 좋을 것 같습니다. 정리된 블로그를 첨부합니다. https://lordofkangs.tistory.com/264

하지만 모든 코드가 저 조언을 따라야하는 건 아니겠지요
서현님이 구현한 것처럼 필요한 경우, 삭제하는 메서드가 삭제한 값을 반환하는 형태로 구현할 수 있어요.
다만 현재는 어떤 값이 반환될지 메서드 명에서 표현하고 있지 않기 때문에, 사용자 입장에서 어떤 값이 나올지 알기 어렵겠죵

저라면 javadoc의 `@return`을 활용해볼 것 같네요

2024-05-22 16:57 UTC, kyY00n reviewed
질문에 답변 남겼어요!

2024-05-22 16:57 UTC, kyY00n commented on src/main/java/roomescape/Reservation.java
> +    @NotBlank(message = "시간은 필수 입력 값입니다.")
와우 👍🏻

2024-05-22 17:10 UTC, kyY00n commented on src/main/java/roomescape/ReservationController.java
> +        long id = queryingDAO.createReservation(newReservation);
ㅎㅎㅎ 제가 사실 서현님 말을 잘 이해하지 못 해서..
우선 DTO를 사용하는 이유를 작성한 어떤 글을 들고왔어요. https://mangkyu.tistory.com/192
참고해서 결정해보세요.

이 이야기는 직접 나눠봐도 좋을 것 같아요

2024-05-25 15:59 UTC, seobbang commented on src/main/java/roomescape/ReservationController.java
> +//        테스트 코드를 위해 기존 ResponseDto를 이용한 코드 주석 처리
앗 미션에서는 테스트 수정이 불가한 줄 알았어요 ㅎㅎ 다음엔 필요에 따라 수정하는 것도 고려해보겠습니다!

2024-05-25 16:33 UTC, seobbang commented
@kyY00n 

> Service 계층이 왜 등장했는지를 찾아주세요.

요 부분에 대해서 좀 이해해보려고 찾아봤는데,
DAO에서는 DB와 직접적인 로직만을 주로 수행하고,
Service에서는 DAO에 구현된 메소드를 가져와서 사용하며 이와 관련된 비즈니스 로직을 사용하는 것 같아요!

제가 이해한 바로는
아무래도 조회, 생성 등의 기능들에서 필요로 하는 비즈니스 로직이 다양한 컨트롤러에서 사용될 가능성이 있다 보니,
Controller 측면에서는 중복된 코드를 줄이고 재사용성을 높이고자,
DAO 측면에서는 관심사 분리를 하고자,
그리고 유지보수성을 높이고자
그 중간인 Service 계층이 생겨난게 아닐까 싶습니다 ㅎㅎ

지금 구현하고 있는 서비스의 경우 각 로직이 중복되어 사용되고는 있지 않으니 굳이 Service 계층을 만들 필요는 없다고 판단되네요!
그치만, 조금만 더 볼륨이 큰 서비스를 만든다면 필수적으로 필요한 계층 분리라는 생각이 듭니당

2024-05-26 07:32 UTC, kyY00n approved these changes

2024-05-27 04:04 UTC, merged