[Spring JDBC 2주차] 장준영 미션 제출합니다.
next-step/spring-roomescape-playground pull request #34
Opened 2023-11-29 11:55 UTC by johnny19991006

2023-11-29 12:32 UTC, Invidam commented on src/main/java/roomescape/Repository/ReservationRepository.java
> +                        rs.getString("name"), rs.getDate("date").toLocalDate(), rs.getTime("time").toLocalTime()));
요런 것도 되는구나

2023-11-30 02:24 UTC, Choi-JJunho requested changes
고생하셨습니다~
전체적으로 잘 작성해주셔서 손볼곳이 거의 없네요!
몇가지 사소한 디테일에 대한 부분 확인 부탁드릴게요

2023-11-30 02:24 UTC, Choi-JJunho commented on src/main/java/roomescape/Repository/ReservationRepository.java
> +    private final SimpleJdbcInsert insert;
SimpleJdbcInsert 👍

2023-11-30 02:24 UTC, Choi-JJunho commented on src/main/java/roomescape/Repository/ReservationRepository.java
> +    }
간결하고 좋네요 👍

2023-11-30 02:24 UTC, Choi-JJunho commented on src/main/java/roomescape/query/ReservationQuery.java
> +    DELETE("delete from reservation where id = ?");
오?! 쿼리를 ENUM으로 분리하셨군요!
꽤나 생소한 방식이라 흥미가 가는데 분리한 이유가 따로 있을까요?

2023-11-30 02:24 UTC, Choi-JJunho commented on src/main/java/roomescape/service/ReservationService.java
> +            throw new IllegalArgumentException("예약된 아이디가 없습니다 id: " + id, e);
꼼꼼한 예외메시지 👍

2023-11-30 02:24 UTC, Choi-JJunho commented on src/main/resources/schema.sql
> +);
<img width="386" alt="image" src="https://github.com/next-step/spring-roomescape-playground/assets/49794401/20f894d4-c103-44ba-9acb-683a778540a3">

> github에서 - 표시를 띄우네요! 왜그럴까요~?
아래 자료를 확인해보고 인텔리제이 설정까지 해보면 좋을 것 같아요
참고자료: https://velog.io/@junho5336/No-newline-at-end-of-file

ditto

2023-11-30 02:24 UTC, Choi-JJunho commented on src/test/java/roomescape/MissionStepTest.java
> +    void 오단계() {
테스트 1,2,3,4단계도 추가해주시면 좋을 것 같아요~

2023-12-03 06:27 UTC, johnny19991006 commented on src/main/java/roomescape/Controller/ReservationController.java
> +        }
4단계에서 다 적용하지 못해서 아직 예외처리가 완벽하지 못했나봅니다!
Handler는 오랜만에 사용해보는거라 다시한번 공부하고 적용해 볼게유!

2023-12-03 06:28 UTC, johnny19991006 commented on src/main/java/roomescape/query/ReservationQuery.java
> +    DELETE("delete from reservation where id = ?");
저도 원래 안쓴 상태였는데, 저번의 clean code스터디에서도 enum을 활용하여 확장성에서의 장점 이 있었고, 다희 코드에서 그러한 흥미로운 enum을 사용하였기에 차용해봤습니다!

2023-12-16 04:46 UTC, Choi-JJunho commented on src/main/java/roomescape/Controller/ReservationController.java
> +        }
해당 부분에 대해서 BindingResult -> ExceptionHandler 적용이 안된것 같은데 확인 부탁드려요~

2023-12-16 04:47 UTC, Choi-JJunho approved these changes
고생하셨습니다~
자잘한 부분 하나 있는데 이 부분은 Core 진행하면서 적용해주시죠!

2023-12-16 04:47 UTC, Choi-JJunho commented on src/main/java/roomescape/Controller/ReservationController.java
> +        }
해당 부분에 대해서 BindingResult -> ExceptionHandler 적용이 안된것 같은데 확인 부탁드려요~

2023-12-16 11:18 UTC, merged