-
next-step/spring-roomescape-playground pull request #362
Opened 2024-11-06 12:15 UTC by shin378378

2024-11-13 01:59 UTC, kokodak requested changes
안녕하세요 혜빈님! 먼저 리뷰가 늦어서 죄송합니다 ㅠㅠ 늦은만큼 더 꼼꼼한 리뷰를 남기려고 해봤어요.

미션 고생 많으셨고, 리뷰 반영하시면서 궁금하신 것 있다면 언제든지 물어봐 주세요.

아래는 혜빈님이 남긴 질문에 대한 답변이에요.

> 궁금한 점:
> 예외처리를 class로 만들어서 해주는 이유가 무엇인가요?
> 제가 보기엔 그냥 바로 예외처리를 해주는 게 빠를 거 같은 데 예외를 객체로 만드는 이유가 궁금합니다!!

여러가지 이유가 있을 것 같아요. 제 생각에는 크게 두 가지의 장점이 있다고 생각합니다.

1. 상황에 맞는 네이밍, 필드 등을 가진 에러를 정의할 수 있다.
2. 세부적인 에러 핸들링이 가능해진다.

> 제가 보기엔 그냥 바로 예외처리를 해주는 게 빠를 거 같은 데

위 문장을 정확히 이해하지 못했지만, '`IllegalArgumentException` 과 같은 기본 에러를 사용하면 안되나?' 하는 질문으로 이해하고 답변을 해볼게요.

현재의 경우에는, 에러 처리에 대해서 다 같은 400 상태 코드를 반환하기 때문에, 어떻게 보면 '불필요한 중복 코드가 아닌가?' 하는 생각을 할 것 같아요.

다만, 같은 일을 하고 있더라도, 서로 다른 상황에서 발생한 에러를 처리하고 있는 로직이기 때문에, 저는 엄밀히 다른 일을 하는 코드라고 생각하는 편이에요.

커스텀 예외를 사용했을 때의 장점은 디버깅이 용이하다는 점도 있을 것 같아요. 아무래도 예외 클래스 네이밍이 현재 비즈니스와 관련된 용어를 사용할 것이고, 이는 장애가 생겼을 때 어떤 에러가 발생했는지를 쉽게 발견해낼 수 있는 장점이 있겠네요.

마지막으로, 세부적인 에러 핸들링이 가능하다는 점이 정말 중요한 포인트인 것 같아요.
상황에 따라서, 어떤 예외인가에 따라서 반환해야 하는 HTTP 상태 코드가 다를 수 있고, 응답으로 나가야 하는 에러 객체의 내용이 다를 수 있어요. 또한 로깅을 한다면, 그에 대한 로깅 레벨도 다를 수 있겠네요.
만약 서로 다른 예외 상황에서 같은 예외를 사용한다면, `@ExceptionHandler` 에서 예외를 세부적으로 나눠서 에러 분기 처리를 할 수 없겠죠.

현재 혜빈님의 상황에서는 에러를 크게 `MissingRequiredFieldException`, `NotFoundReservationException` 두 개로 나누어주셨는데, 커스텀 에러를 나누어준 덕분에 에러 분기 처리가 가능해요.
이를테면, `MissingRequiredFieldException` 인 경우 400 에러, `NotFoundReservationException` 인 경우 404 에러를 반환해볼 수도 있겠죠.

위와 같은 장점들이 꽤 크게 작용해서, 커스텀 예외를 직접 정의해서 많이 사용하는 것 같아요.

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/Reservation.java
> +    }
메서드들도 숨 좀 쉬게 서로 한 칸씩 간격을 두면 좋겠어요 ㅎㅎ

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +        reservations.add(new Reservation(3L, "브라운", "2023-01-03", "12:00"));
더미 데이터를 넣는 것은 실제 운영 테스트를 할 때 도움이 되지만, 이 때문에 기존의 테스트 코드가 깨지고 있네요.

개인 로컬에서는 이런 종류의 코드를 넣는 것이 큰 상관이 없지만, 원격 저장소에 push 하는 코드에서는 위험할 수 있어요.

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +    @RequestMapping("/reservations")
```suggestion
    @GetMapping("/reservations")
```

`@RequestMapping` 보다는, `@GetMapping` 어노테이션을 사용하는 것이 더 직관적일 것 같아요.

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
Id를 AtomicLong 과 같은 카운터 변수를 통해 관리해보는 건 어떨까요?

현재 코드는 추후에 여러 가지 문제점을 일으킬 수 있는데, 어떤 점이 문제가 될 수 있을지 고민해 보세요. 그리고 그 이후에 같이 논의해 보죠!

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
요청 DTO를 잘 검증해주셨네요! 👍 null 여부를 먼저 검증하는 디테일도 좋았습니다.

여기서 한가지 생각해보면 좋을 것이 있는데, 바로 '검증부의 위치' 예요.

혜빈님은 DTO 필드 값에 대한 검증부 로직이 어떤 곳에서 수행되어야한다고 생각하시나요?

저는 DTO의 경우에, 최대한 빠르게 검증하는 편이 좋다고 생각해서 DTO 레벨에서 바로 검증을 하는 것 같아요.

이를 위해서, 스프링 기술 중 하나인 `@Valid` 어노테이션을 사용해볼 수도 있어요.

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +        return ResponseEntity.created(location).body(reservation);
자원 생성에 성공했을 때, 201 응답과 적절한 Location 헤더를 함께 내려주는 것이 너무 좋네요! 👏👍

덕분에 함께 협업하는 클라이언트 개발자가, 이 생성된 자원에 대한 정보를 활용해서 접근해볼 수도 있겠어요.

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +    public ResponseEntity<?> addReservation(@RequestBody addReservationRequest reservationRequest) {
제네릭에 와일드카드(`<?>`)를 넣어서 반환하고 있네요! 이럴 때의 장점과 단점에는 무엇이 있을까요?

저는 개인적으로, 응답할 ResponseEntity의 제네릭에는 명확한 클래스 타입이 들어가는 게 좋다고 생각해요.
지금의 상황에서는 와일드카드의 유연성이 필요해 보이지 않고, 협업하는 사람의 관점에서 `그래서 이 API는 어떤 걸 반환한다는 거지?` 라는 의문을 살 수 있어요.

제네릭에 들어갈 타입을 다시 고민해보시면 좋겠습니다.

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +    @ResponseBody
어떤 곳에는 `@ResponseBody` 가 붙어있고, 어떤 곳에는 안 붙어있네요. 일관성을 지키는 것이 좋겠어요.

(참고) ResponseEntity 를 반환할 경우, `@ResponseBody` 어노테이션이 없어도 괜찮아요.

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +    }
Controller를 크게 두 가지 측면에서 나눠볼 수 있을 것 같아요.

하나는 static 페이지 리소스에 접근하는 Controller, 다른 하나는 혜빈님이 정의한 메서드 로직을 통해 가공된 데이터를 반환하는 Controller 로요.

어떻게 보면 책임이 다르다고 볼 수도 있을 것 같은데, Controller 를 분리해보는 건 어떨까요?
하나는 `@Controller`, 다른 하나는 `@RestController` 로 나눠볼 수 있을 것 같아요.

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/dto/addReservationRequest.java
> +public class addReservationRequest {
```suggestion
public class AddReservationRequest {
```

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/dto/addReservationRequest.java
> +    private String time;
DTO를 불변으로 만들기 위해서, 필드에 final을 붙이는 것이 좋을 것 같아요.

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/exception/NotFoundReservationException.java
> +public class NotFoundReservationException extends RuntimeException {
Custom Unchecked Exception을 잘 만들어주셨네요 👍👍

덕분에 세부적인 에러 핸들링이 가능해질 것 같아요.

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +    }
예외 처리를 잘 해주셨네요!

한 가지 더 알려드리고 싶은 점은, 에러 처리도 클래스를 분리해서 책임을 분산시킬 수 있어요. 정상 동작하는 케이스와 예외 처리 케이스를 분리시키는 거죠.

@ControllerAdvice 라는 어노테이션을 통해서 전역적인 에러 처리를 구현할 수 있는데, 아래의 글을 공부해보시면 좋겠어요.
https://tecoble.techcourse.co.kr/post/2023-05-03-ExceptionHandler-ControllerAdvice/

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +        throw new NotFoundReservationException("해당 ID의 예약이 존재하지 않습니다.");
로직의 흐름이 고쳐지면 좋을 것 같아요.

보통 성공 케이스를 가장 나중에 반환하고, 예외적인 케이스는 if 분기 조건에서 반환하는 것이 좋아요. 예외가 언제 발생하는 지를 한눈에 보이게 구현하는 게 중요하니까요.

별개로, 프로그래밍 요구사항에서는 사라졌지만, 그동안 우리가 indent depth를 줄이기 위해 노력해온 것을 적용해보면 좋을 것 같아요!

2024-11-13 01:59 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +    }
위에 있는 예외 처리 메서드와 비슷한 일을 하는 것 같은데, 코드 구현부가 다르네요. 컨벤션을 통일하는 것이 좋겠어요!

2024-11-18 12:24 UTC, shin378378 commented on src/main/java/roomescape/reservation/Reservation.java
> +    }
ㅋㅊㅍㅌㅊㅍㅌㅋㅌㅊㅍㅌ 하하 메소드 숨 좀 쉬게 ㅋㅍㅌㅋㅌㅊㅍ
확 와닿네요!! 수정했습니다 :)

2024-11-18 12:28 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        reservations.add(new Reservation(3L, "브라운", "2023-01-03", "12:00"));
잘 출력이 되나 확인하려고 임시로 적어둔 값인 데 빼는 걸 깜빡했네요!!
짚어주셔서 감사합니다. 지금은 값을 제거 하였습니다 :)

2024-11-18 12:40 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +    @RequestMapping("/reservations")
`@RequestMapping`과 `@GetMapping`의 차이점에 대해 잘 몰랐는 데

1. `@RequestMapping`
모든 HTTP 메서드 지원, 특정 기능만을 지원하려면 추가 method 속성 설정필요

2. `@GetMapping`
GET 요청만 처리 지원

즉, `@GetMapping`이 `@RequestMapping`보다 좀 더 좁은 범위를 지원하는 군요!
어떤 역할을 하는 지 직관적으로 알려면 리뷰어는 말씀처럼 `@GetMapping`이 좀 더 적합할 거 같네요!!
짚어주셔서 감사합니다 :)

2024-11-18 12:57 UTC, c0mpuTurtle commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
``` java
private long getNextId() {
        return idGenerator.getAndIncrement();
    }
```
리뷰어님의 조언을 바탕으로 위와 같이 코드를 수정하였습니다!!

2024-11-18 13:01 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
1. `reservations.get(reservations.size() - 1).getId() + 1;`
2. `atomicLong.getAndIncrement();`

제가 사용한 방식인 1번:
1. id를 생성할 때마다 마지막 요소 확인이 필요
2. 멀티스레드 환경에서는 동시 접근 시 리스트의 상태가 변경될 수 있어 문제가 발생할 가능성 있음

리뷰어님께서 추천한 방식인 2번 :
1. ID 생성 로직이 별도로 필요하지 않아 O(1) 성능을 제공 
2. 스레드-안전(Thread-safe)하며 동시성 문제 없음

이렇게 특징도 알아봤는 데 
`AtomicLong`을 쓰면 ID를 생성할 때마다 마지막 요소 확인이 필요하지 않아 성능이 향상된다는 점은 예상했지만
동시성 문제를 해결할 수 있다는 점은 예상하지 못 해서

2024-11-18 13:36 UTC, c0mpuTurtle commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
사실 딱히 별 이유없이 `null` 여부 먼저 검사한 거 였는 데 `null` 여부 먼저 검증했다고 칭찬해주셔서
왜 `null`을 먼저 검사해야하는 지 찾아보았는데요.

1.`null` : 변수는 선언되었지만 아직 아무 값도 참조하지 않는 상태
2.`isEmpty` : 참조하는 값이 있지만 값의 길이가 0인 경우
즉, 값이 `null`인데 `isEmpty`메소드를 쓰게 되면 `NullPointerException`이 발생하기 때문에 `isEmpty`보다 `null`를 먼저 검사해주어한다.

위와 같은 정보를 알게 되었습니다! 오늘도 새로운 거 배워갑니당 :)

2024-11-18 13:43 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
## <질문>
```
if (name == null || name.isEmpty() || data == null || data.isEmpty() || time == null || time.isEmpty())
```
위와 같은 코드를 대체하기 위해
```java 
public ResponseEntity<?> addReservation(@RequestBody @Valid AddReservationRequest reservationRequest)
```
위와 같이 `@Valid`를 사용해 값이 null인 경우를 사전에 방지하고

``` java
@NotEmpty(message = "이름은 필수 값입니다.")
    private String name;
    @NotEmpty(message = "날짜은 필수 값입니다.")
    private String date;
    @NotEmpty(message = "시간은 필수 값입니다.")
    private String time;
```
    위와 같이 `@NotEmpty`를 사용해 isEmpty인 경우를 방지해주었습니다.
    이런식으로 활용하

2024-11-18 13:52 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +    public ResponseEntity<?> addReservation(@RequestBody addReservationRequest reservationRequest) {
반환 값이 Reservation 객체이므로, ResponseEntity<Reservation>를 사용하는 것이 좋겠네요

2024-11-18 13:58 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        return ResponseEntity.created(location).body(reservation);
```
HTTP/1.1 201 Created
Location: /reservations/12345
Content-Type: application/json

{
  "id": 12345,
  "name": "John Doe",
  "date": "2024-11-20",
  "time": "18:30"
}
```
사실 장점을 알고 쓴 건 아니였는 데 위와 같이 응답이 생성되면 
자원이 제대로 생성된 게 맞는 지와 생성된 자원의 url을 파악하기에 확실히 편할 거 같아요!!
좋은 방법이였군요!! 앞으로도 적극적으로 활용해보도록 하겠습니다!!

2024-11-18 14:14 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +    @ResponseBody
이번 기회를 통해 `@ResponseBody`와 `ResponseEntity`에 대해 알아보았습니다.

`@ResponseBody` :
`ResponseEntity` :

2024-11-19 03:13 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +    @ResponseBody
`ResponseEntity` 자체가 HTTP 응답을 표현하는 객체로 설계되었기 때문에 굳이 `@ResponseBody` 없군요!!
새로운 정보를 알아갑니당 :)

2024-11-19 03:20 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +    }
Controller가 하나의 책임만 가지도록 해야한다는 점을 간과한 거 같아요

2024-11-19 03:20 UTC, shin378378 commented on src/main/java/roomescape/reservation/dto/addReservationRequest.java
> +public class addReservationRequest {
수정완료 하였습니당!!

2024-11-19 03:35 UTC, shin378378 commented on src/main/java/roomescape/reservation/dto/addReservationRequest.java
> +    private String time;
저는 `final`을 붙이려면 바로 `final private String name="그리디";  이런식으로 초기화를 해줘야한다고 생각했는 데
생성자를 통해 초기화할 때도 final을 붙일 수 있는 지는 몰랐네요!!
감사합니다 :) 수정완료 하였습니다 !

2024-11-19 07:41 UTC, shin378378 commented on src/main/java/roomescape/reservation/exception/NotFoundReservationException.java
> +public class NotFoundReservationException extends RuntimeException {
앗 저 에러는 제가 만든 게 아니라 원래 있던 에러처리 코드입니다 ㅎㅎㅎ!!
사실 별 생각 없이 넘어갔는 데 저렇게 특정 에러 핸들링이 가능하도록 처리해줄 수도 있군요!!
덕분에 짚고 넘어갑니다 감사합니다 :)

2024-11-19 08:12 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        throw new NotFoundReservationException("해당 ID의 예약이 존재하지 않습니다.");
성공 케이스를 가장 나중에 반환하는 게 좋다는 관점은 생각해보지 못 한 거 같아요!
성공보다는 예외를 처리해줘야 예외가 언제 발생하는 지 직관적으로 보이는 군요!!
아래와 같이 예외케이스를 if로 반환해주었습니다 :)

``` java
for (Reservation reservation : reservations) {
            if (reservation.getId() != id) {
                continue;
            }
            reservations.remove(reservation);
            return ResponseEntity.status(HttpStatus.NO_CONTENT).body("예약이 취소되었습니다.");
        }
        throw new NotFoundReservationException("해당 ID의 예약이 존재하지 않습니다.");
```
추가적으로 depth를 줄이기 위해 continue를 사용해주었습니다.

2024-11-19 08:18 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +    }
다음과 같이 상태 코드를 명확히 표현하는 `HttpStatus.BAD_REQUEST`로 컨벤션을 통일해주었습니다!
컨벤션을 통일하는 게 코드의 일관성을 유지하는 데 더 좋은 거 같아요! 
이런 세세한 부분까지 짚어주셔서 감사합니다 :)
```java
@ExceptionHandler(NotFoundReservationException.class)
    public ResponseEntity<String> handleNotFoundReservationException(NotFoundReservationException e) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
    }

    @ExceptionHandler(MissingRequiredFieldException.class)
    public ResponseEntity<String> handleMissingRequiredFieldException(MissingRequiredFieldException e) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
    }
 ```

2024-11-19 09:48 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +    }
이렇게 따로 클래스를 만들어 예외 처리 케이스를 분리해주었습니다!
```
@ControllerAdvice
public class GlobalExceptionHandler {
    @ExceptionHandler(MissingRequiredFieldException.class)
    public ResponseEntity<String> handleMissingRequiredFieldException(MissingRequiredFieldException e) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
    }

    @ExceptionHandler(NotFoundReservationException.class)
    public ResponseEntity<String> handleNotFoundReservationException(NotFoundReservationException e) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
    }
}
```

2024-11-19 09:54 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +    }
이번 기회를 통해 왜 `@ControllerAdvice`를 쓰는 것이 좋은 지 공부해보았습니다.

`@ControllerAdvice`의 장점 :
1. 모든 컨트롤러에서 발생하는 예외를 한 곳에서 처리 가능 <- 중앙집중화
2. 전역 예외 처리 클래스에서 응답 형식을 통일 가능 <- 일관성
3. 새로운 예외를 처리하려면 `@ControllerAdvice` 클래스에만 예외 처리 메서드를 추가하면 됨 <- 유지보수 향상
4. `@ExceptionHandler`를 통해 특정 예외와 범용 예외를 분리하여 처리 가능

`@ControllerAdvice`는 처음 들어보는 개념인 데 덕분에 중요한 개념을 알아가는 것 같습니다. 감사합니다 :0

2024-11-19 09:57 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +    }
이렇게 따로 클래스를 만들어 예외 처리 케이스를 분리해주는 로직으로 수정해주었습니다!!
```
@ControllerAdvice
public class GlobalExceptionHandler {
    @ExceptionHandler(MissingRequiredFieldException.class)
    public ResponseEntity<String> handleMissingRequiredFieldException(MissingRequiredFieldException e) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
    }

    @ExceptionHandler(NotFoundReservationException.class)
    public ResponseEntity<String> handleNotFoundReservationException(NotFoundReservationException e) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
    }
}
```

2024-11-19 11:39 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
와우... 놀랐어요
하고 싶었던 말을 잘 적어주셨네요 👍👍👍

시간이 되신다면, AtomicLong은 어떻게 원자적 연산을 제공하는지 찾아보시면 좋을 것 같아요. (키워드: `CAS 알고리즘`)

2024-11-19 11:46 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
굿굿 👍👍 잘 해주셨어요

조금 더 정확하게 짚자면, `@Valid` 어노테이션이 null 인 경우를 방지해준다기보다, `@NotEmpty` 어노테이션이 이를 방지한다고 보는게 정확할 것 같아요.

한 가지 더 얘기해보면, `@NotEmpty` 와 `@NotBlank` 의 차이를 파악해보고 둘 중 어떤 것을 사용하는 것이 더 좋을지 고민해보면 좋겠습니다!

2024-11-19 11:49 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +        return ResponseEntity.created(location).body(reservation);
Location 헤더는 클라이언트 개발자가 자연스러운 UI/UX 화면 흐름을 구성하기 위해 특히나 중요한 헤더예요.

2024-11-19 11:57 UTC, kokodak commented on src/main/java/roomescape/reservation/exception/NotFoundReservationException.java
> +public class NotFoundReservationException extends RuntimeException {
앗 그렇군요 ㅎㅎ.. 커스텀 예외는 사실상 필수적이니 잘 보고 넘어가면 좋겠어요!

2024-11-19 12:26 UTC, kokodak requested changes
리뷰 너무 잘 반영해주셨습니다 혜빈님 👍👍

힘드셨을텐데 고생 많으셨어요.

한 가지 리뷰 코멘트 의도가 잘 전달되지 않은 것 같아서, 그 부분에 대해서 다시 코멘트를 드렸어요. 코드도 함께 첨부했으니, 그 부분만 반영해주시고 재리뷰요청 주시면 바로 Approve 하도록 하겠습니다~!

2024-11-19 12:26 UTC, kokodak commented on src/main/java/roomescape/reservation/controller/ReservationApiController.java
> +    }
```suggestion
@DeleteMapping("/{id}")
    public ResponseEntity<String> deleteReservation(@PathVariable int id) {
        Reservation reservation = reservations.stream()
                                              .filter(reserv -> reserv.getId() == id)
                                              .findFirst()
                                              .orElseThrow(() -> new NotFoundReservationException("해당 ID의 예약이 존재하지 않습니다."));

        reservations.remove(reservation);
        return ResponseEntity.status(HttpStatus.NO_CONTENT).body("예약이 취소되었습니다.");
    }
```

<img width="1164" alt="image" src="https://github.com/user-attachments/assets/3160fab1-e6a4-4672-bedc-21151c6f3ef7">

(사진은 위의 suggestion code와 같은 코드입니다. 예쁘게 안 보이는 것 같아서 사진도 첨부했어요!)

제가 리뷰를 모호하게 적었던 것 같아요.

혜빈님께 전달드리려고 했던 내용은, 예외를 throw 하는 로직을 맨 마지막에 하지 않았으면 좋겠다는 의미였어요.

로직의 맨 마지막 부분에는 throw 보다, 성공적으로 return 하는 로직이 보이는 것이 좋을 것 같습니다. 그 이유는 스터디 때 언급했던 것처럼, 언제 예외가 던져지는지를 최대한 직관적으로 쉽게 파악할 수 있어야 하기 때문이에요.

현재의 로직 흐름에서는, for문과 if문 로직을 모두 통과했을 경우에 예외가 던져지는데, 이를 파악하기가 만만하지 않다는 문제가 있어요. 즉, 언제 예외가 발생하는지 파악하기가 어렵다는 뜻이겠죠. 이는 장애가 발생했을 경우 디버깅을 하기 어렵게 만드는 요인이 될 수 있어요.

제가 원했던 로직의 흐름은 첨부한 사진과 같은 흐름이에요. 예외를 먼저 던지고, 성공 케이스를 밑에 적는 거죠.

2024-11-19 12:26 UTC, kokodak commented on src/main/java/roomescape/reservation/exception/GlobalExceptionHandler.java
> +    }
`@ControllerAdvice` 에 대해 드렸던 리뷰를 너무 잘 반영해주셨어요!

한 가지 알고 있으면 좋을 점은, 현재는 `MissingRequiredFieldException`, `NotFoundReservationException` 외의 예외가 발생했을 경우 잘 대처가 되지 않는다는 점이에요. (예를 들어 `IllegalArgumentException`와 같은 예외)

다만, 혜빈님이 모든 예외에 대해 에러 처리를 하는 것은 현실적으로 불가능하기 때문에, 개발자가 의도하지 않은 예외가 발생한 경우 이를 한번에 묶어서 처리할 수 있는 방법이 있어요.

바로 `Exception.class` 자체를 잡아서 핸들링 하면 됩니다. 그러면 혜빈님이 의도하지 않은 예외가 터지더라도, 원하는 응답코드와 메세지를 클라이언트에게 내려줄 수 있어요. 이때는 보통 의도하지 않은 서버 에러이기 때문에, 500번대 응답 코드와 함께 에러를 클라이언트에게 응답해줍니다.

+) `@ExceptionHandler` 를 통해 처리되는 예외는 기본적으로 specific 한 예외에 대한 우선순위가 더 높아서, 모든 예외가 한 곳에서만 처리되는 일은 일어나지 않아요.

2024-11-19 12:27 UTC, kokodak commented on src/main/java/roomescape/reservation/exception/GlobalExceptionHandler.java
> +    }
이 리뷰는 JDBC 미션에서 반영해주셔도 좋아요. 그냥 알고 있으면 좋겠다~ 하는 생각에 남긴 리뷰입니다.

2024-11-20 12:10 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
Atomic은 CAS를 알고리즘을 사용하네요!!

Compare-And-Swap(CAS) 알고리즘이란?

CAS는 동기화 없이 원자적 연산을 수행하는 방식으로 다음의 과정을 거칩니다.
1. 현재 값을 읽음
2. 만약 현재 값이 예상 값과 일치하면, 새 값으로 교체 / 일치하지 않으면 아무 작업도 수행하지 않고 실패를 반환

이 과정은 하드웨어 명령으로 보장되기 때문에 스레드 간 충돌이 없도록 설계됩니다.
CAS는 스레드 간의 락(lock)을 사용하지 않기 때문에, 성능 저하 없이 데이터 일관성을 보장합니다.

2024-11-20 12:34 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
앗 제가 잘못 이해했네요 ㅜㅠ

`@Valid`:
어노테이션 자체가 유효성 검사를 실행하지 않고 객체 내부의 필드나 값들에 대해 추가적인 검사를 실행할 지를 결정합니다.
ex)
```
@Valid
private SomeObject someObject; // someObject의 필드에 붙은 제약 조건들을 검사함
```
@NotEmpty 어노테이션:

직접적으로 null 값이나 빈 값을 방지하는 제약 조건입니다.
null뿐만 아니라 빈 문자열(""), 빈 컬렉션 등도 허용하지 않습니다.
따라서 해당 어노테이션이 적용된 필드에 대해 실제로 null인지, 비어 있는 값인지 확인하여 예외를 발생시킵니다.
java
코드 복사
@NotEmpty
private String name; // name이 null이거나 ""이면 유효성 검사 실패
왜 "null 방지는 @NotEmpty가 한다"고 표현했을까?
@Valid는 객체 내부의 제약 조건을 활성화시킬 뿐, 객체 자체가 null인지 아닌지는 검사하지 않습니다. 따라서 객체가 null일 경우, @Valid 자체는 유효성 검사를 수행하지 못합니다.
반면, @NotEmpty는 null을 방지하는 구체적인 제약 조건을 명시적으로 제공합니다.
따라서 null 값을 방지하는 역할은 @NotEmpty와 같은 제약 어노테이션이 수행한다고 보는 것이 더 정확합니다.

2024-11-20 12:35 UTC, c0mpuTurtle commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
< `@NotEmpty` 와 `@NotBlank` 의 차이 >

`@NotEmpty` :
null이 아니어야 함
빈 문자열("")이 아니어야 함

`@NotBlank` :
null이 아니어야 함
빈 문자열("")이 아니어야 함
* 중요) 공백만 포함된 문자열(" ")도 허용하지 않음
* 예를 들어 사용자 이름, 비밀번호처럼 실제 값을 입력해야 하는 상황에 많이 사용

즉, 둘의 차이점은 
`@NotEmpty`인 경우 " "와 같은 공백값만  입력 가능하지만 `@NotBlank`인 경우 " "와 같은 공백값만 입력하는 것이 불가능하다는 것입니다.

2024-11-20 12:48 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
제가 개념을 많이 잘못 알고 있었네요 ㅎㅎㅎ
짚어주셔서 감사합니다! 하마터면 잘못 알고 갈 뻔 했네요 ㅜㅠ

2024-11-20 12:51 UTC, c0mpuTurtle commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
`@NotBlank`로 어노테이션 수정하였습니다!!

2024-11-20 12:58 UTC, shin378378 commented on src/main/java/roomescape/reservation/ReservationController.java
> +        return ResponseEntity.created(location).body(reservation);
Location 헤더가 자연스러운 UI/UX 화면 흐름과 무슨 연관이 있나 이해를 못 했는 데 

1. Location 헤더가 있을 경우:
Location 헤더를 통해 반환된 url주소를 통해 클라이언트는 화면을 전환하기 때문에 클라이언트가 따로 url이동 로직을 짜지 않아도 된다.

2. Location 헤더가 없을 경우:
클라이언트는 서버로부터 명시적인 이동 지시를 받지 못하기 때문에 클라이언트가 따로 브라우저를 이동시키는 로직을 구현해야한다.

2024-11-20 13:12 UTC, shin378378 commented on src/main/java/roomescape/reservation/controller/ReservationApiController.java
> +    }
앗 예외처리문 자체를 성공케이스 앞에 놔두길 바라셨군요!!
제가 이해를 잘못했나 봐요 ㅎㅎㅎ

다시 이해를 해봤습니당!!
---
문제점 :
예외를 던지는 로직이 로직의 맨 마지막에 위치해 예외가 언제 발생하는 지 한눈에 파악하기 어렵다.

제안된 개선 방향 :
구조 ) 예외를 먼저 처리하고 성공 로직은 뒤에 두는 구조
효과 )예외 발생 조건을 가장 먼저 확인할 수 있어 예외가 언제 발생하는 지 한 눈에 파악하기 쉽다.
(이를 흔히 "예외 먼저 처리 (Guard Clause)"라고 부름)

-> 핵심 : 가독성을 위해 예외를 먼저 처리하고, 성공 케이스는 뒤에 둬라.
---

이에 대한 이해를 바탕으로 리뷰어님께서 적어주신 코드로 수정완료하였습니다!!

2024-11-20 13:29 UTC, shin378378 commented on src/main/java/roomescape/reservation/exception/GlobalExceptionHandler.java
> +    }
`@ExceptionHandler(Exception.class)`에 대해 처음 들어보았는 데
Exception.class를 핸들러로 지정해주면 예상치 못한 모든 예외에 대해 클라이언트에게 적절한 응답을 보낼 수 있군요.

특히,
특정 예외 → 해당하는 핸들러가 우선적으로 처리
나머지 모든 예외 → Exception.class 핸들러에서 처리한다는 점이 인상깊었습니다.

Exception 처리에도 우선순위가 있는 줄은 몰랐어요 ㅎㅎㅎ

```java
@ExceptionHandler(Exception.class)
    public ResponseEntity<String> handleGlobalException(Exception e) {
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body("에러발생: " + e.getMessage());
    }
    ```
    위와 같은 코드를 추가해 예상치 못한 오류에도 대응할 수 있도록 해주었습니다 !! 마지막까지 감솨합니당!!

2024-11-21 00:30 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +        }
어렵다면 이 코멘트는 무시하셔도 됩니다.

정확히 말하자면, CAS 연산은 하드웨어 레벨에서 메모리 락을 사용하긴 합니다. CAS 연산 요청이 동시적으로 발생해도, 하드웨어 레벨에서 이를 직렬화 시켜서 하나씩 처리해요. 말씀 주신대로, 자바에서 구현된 Atomic 클래스들은 CAS 연산을 통해 락을 사용하지 않고도 원자적 연산을 해낼 수 있어요. 자바에서는, CPU cache로 인한 메모리 동기화 문제가 발생할 수 있어서 volatile 키워드를 사용해서 이를 방지하기도 합니다.

락을 사용하지 않고 원자적 연산을 하는 CAS 알고리즘의 컨셉은, 이후에도 다른 형태로 종종 등장할 거예요. (Spring Data JPA에서도 같은 개념을 차용합니다.) CAS 연산은 매우 중요한 연산이기도 하고, 그 컨셉이 다른 기술에서도 보이기 때문에 언급드렸습니다.

2024-11-21 00:39 UTC, kokodak commented on src/main/java/roomescape/reservation/ReservationController.java
> +        return ResponseEntity.created(location).body(reservation);
정확합니다 신박사님

2024-11-21 00:43 UTC, kokodak approved these changes
LGTM :)

2024-11-21 06:28 UTC, merged