[Spring MVC] 남해윤 미션 제출합니다
next-step/spring-roomescape-playground pull request #363
Opened 2024-11-06 14:40 UTC by haeyoon1

안녕하세요 백경환 멘토님! 스프링 미션은 처음인데 잘 부탁 드립니다.
부족한부분 리뷰 남겨주시면 열심히 수정하겠습니다. 감사합니다:)

test를 돌리면서 두 가지 문제가 있었는데요
1. 2단계 test를 실행할 때와, 3단계 test를 실행할 때 변수 초기화 관련 문제
2단계 test를 돌릴때는 ReservationController에 
```
@Controller
public class ReservationController {

    public ReservationController() {
        reservations.add(new Reservation(1L, "브라운1", "2023-01-01", "10:00"));
        reservations.add(new Reservation(2L, "브라운2", "2023-01-02", "11:00"));
        reservations.add(new Reservation(3L, "브라운3", "2023-01-03", "12:00"));
    }
}
```
해당 생성자를 만들어 3개의 값을 넣은 상태로 문제를 풀었는데, 이렇게 데이터가 들어간 상태로 삼단계를 실행하면 오류가 발생하더라고요.  test코드의 삼단계 메서드의
```
params.put("name", "브라운");
params.put("date", "2023-08-05");
params.put("time", "15:40");
```
해당부분이 id가 1로 지정되어 들어가는 것 같아서 아래의 모든 .body("size()", is(1));부분의 is() 속 개수를 수정해도 
예약 추가를 실행하면 [예시1]과 같은 결과가, 예약 취소를 실행하면 [예시2]과 같은 결과가 출력됩니다. 그래서 삼단계 테스트를 진행할때에는 RestController의 생성자 부분을 주석처리했는데 이렇게 코드를 작성해도 괜찮은 것일까요?
**[예시1]**
```
[
    {
        "id": 1,
        "name": "브라운1",
        "date": "2023-01-01",
        "time": "10:00"
    },
    {
        "id": 2,
        "name": "브라운2",
        "date": "2023-01-02",
        "time": "11:00"
    },
    {
        "id": 3,
        "name": "브라운3",
        "date": "2023-01-03",
        "time": "12:00"
    },
    {
        "id": 1,
        "name": "브라운4",
        "date": "2023-08-05",
        "time": "15:40"
    }
]
```

**[예시2]**
```
[
    {
        "id": 2,
        "name": "브라운2",
        "date": "2023-01-02",
        "time": "11:00"
    },
    {
        "id": 3,
        "name": "브라운3",
        "date": "2023-01-03",
        "time": "12:00"
    },
    {
        "id": 1,
        "name": "브라운4",
        "date": "2023-08-05",
        "time": "15:40"
    }
]
```

2. local환경에서 실행했을 때에는 id값이 하나씩 증가하며 예약 추가가 되지만, [예시1] 같은 경우에 콘솔창에서의 결과값을 보면, id가 자동으로 1로 등록돼서 추가되는데, 이전의 id값을 보고 자동으로 알맞은 id값을 찾아서 추가하는 것으로 코드를 수정해야하는것인지 궁금합니다!

그리고 추가로 요즘 커밋메세지 날리는 방법에 대해 신경쓰려하고 있는데, 더 세세하게 나누어서 커밋을 보내는게 맞을까요?

2024-11-09 16:37 UTC, dooboocookie requested changes
해윤님, 안녕하세요.
리뷰어 루카입니다.🐳

일단 PR 올리신 것에 비해 너무 늦게 리뷰를 드린 것 같아 죄송합니다.

앞서 금서님 리뷰를 진행했는데, 제가 이번 MVC 미션 관련 범위를 명확하게 인지를 못하고 앞으로 어떤 미션들이 있을지 모르는 상태였어서, 약간의 스포성 리뷰를 했었는데요. [궁금하시면 봐도 좋을 것 같아요.](https://github.com/next-step/spring-roomescape-playground/pull/367)

그리고 금서님과 코드가 거의 비슷해서 복붙도 좀 했습니다.

## 🐳 리뷰 스타일
아무래도 리뷰어-리뷰이로 첫 만남이니 제 리뷰 스타일이나 지향점을 말씀드리겠습니다.
일단 여러 미션들을 거치면서 아셨겠지만, 모든 것은 정답이 없는 문제들이죠.
일단 잘 돌아가는것이 중요합니다.
그치만 저희가 이렇게 번거롭고 까다롭게 미션을 진행하는 이유는 코드를 더 잘 작성하는 연습을 하기 위해서죠.
**코드를 왜 잘 짜야할까요? 해윤님은 이 미션 과정들을 통해서 어떻게 성장하고 싶으신가요? 생각을 들려주세요.**
저는 이 학습 목표를 통해서 해윤님의 코드가 `확장이 용이한 코드가 됐으면 좋겠다`는 목표들로 리뷰를 진행할 것입니다.
그래서 "이렇게 해주세요!"라고 말씀 드리는 경우는 정말 없을거에요. 질문을 많이 드렸으니, 한번 저에게 설명부탁드려요.
재미있게 생각 나눠보아요!

## 🎯 리뷰 포인트
1. 컨트롤러 쪼개기
2. API 명세
3. DTO 이대로 괜찮은가?


## 🔮 질문에 대한 답변
> RestController의 생성자 부분을 주석처리했는데 이렇게 코드를 작성해도 괜찮은 것일까요?

불필요하다고 느껴지시면 과감히 지우세요!
세상의 대부분의 요구사항은 사람이 작성한 것이라 딱 떨어지지 않는답니다.
어떨땐 개발자 스스로 판단해야될때가 많아요.
늘 방법보다 바라보고 있는 문제를 먼저 생각하면 좋을 것 같아요. 학습테스트는 스프링을 연습할 가이드를 주기 위한 수단일 뿐이라고 생각해요.


> local환경에서 실행했을 때에는 id값이 하나씩 증가하며 예약 추가가 되지만, [예시1] 같은 경우에 콘솔창에서의 결과값을 보면, id가 자동으로 1로 등록돼서 추가되는데, 이전의 id값을 보고 자동으로 알맞은 id값을 찾아서 추가하는 것으로 코드를 수정해야하는것인지 궁금합니다!

만약 지금 주석 처리를 해놓은 기본 값 세팅 코드를 살려야 한다면 아이디가 중복되겠네요.
아이디가 유니크하지 않은 것은 정말 심각한 버그입니다.
고쳐야겠죠. 어떤 부분을 어떻게 고치실지는 해윤님이 생각해보시는게 좋겠어요.

> 요즘 커밋메세지 날리는 방법에 대해 신경쓰려하고 있는데, 더 세세하게 나누어서 커밋을 보내는게 맞을까요?

해윤님은 왜 커밋 메시지에 대해서 신경을 쓰고 계신가요?
커밋 메시지를 남기는 목적에 따라 이 질문에 답변은 크게 달라질 것 같은데요.
먼저 제 주관적인 목적과 그에 따른 답변을 해보겠습니다.

1. Save point
2. 팀원(혹은 미래의 나)이 빠르게 작업내용을 파악할 수 있도록

1번은 당연한 내용이고 2번은 1번의 의미를 더 강하게 한다 생각해요.
만약 방탈출 예약 서비스에 기능을 붙여서 서비스 중인데, 아이디가 중복돼서 유저가 다른 유저의 예약을 삭제하는 심각한 버그가 발생했어요. 
그럼 저는 제가 돌아갈 위치를 커밋으로 볼거에요. 버그 fix 전에 해야할 것은 rollback이니까요.
그때 잘알아볼 수 있어야합니다.
더 작은 단위가 좋겠어요. 원자성이 있어야해요. 한 커밋에 확실히 한 동작.
어느 커밋 지점으로 돌아가도 온전한 코드여야돼요. 애써 롤백했는데, 그순간에도 버그가 나고있음 곤란하겠죠...

커밋에 대한 제 의견은 이렇습니다. 해윤님이 생각하시는 커밋에 대해서 말씀해주세요.

---

일단 늦게 리뷰를 드려 정말 죄송합니다 ㅠㅠㅠㅠ
그리고 이번 MVC에서는 다들 비슷하게 코드를 작성하신 것 같아서, 뭔가 많은 얘기를 나누기가 쉽지 않네요. 
제가 어쩌면 MVC미션에서 제시하는 기준을 많이 벗어난 리뷰를 했을수도 있다고 생각합니다.
원래 리뷰라는 것이 그렇지만 꼭 적용해라, 바꿔라, 라는 것은 아니니 읽어보시고 생각을 남겨주시면 좋을 것 같아요.
일단 RC 드릴게요.

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/controller/ReservationController.java
> +@Controller
**[Comment]**

ControllerAdvice에는 RestControllerAdvice를 사용해주셨더라구요.
혹시 Controller 어노테이션과 RestController 어노테이션의 차이를 알고 계신가요?

이 컨트롤러에는 RestController는 사용하지 않으신 이유가 있으신가요?

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/controller/ReservationController.java
> +//    }
넵 이 코드는 지우는것이 맞아보입니다.

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
**[Comment]**

이 두 메서드의 동작 원리를 저한테 한번 설명해주실 수 있으실까요?

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/controller/ReservationController.java
> +                .body(reservation);
(금서님과 동일하게 작성해주셔서 복붙하겠습니다)
**[Approve]**

WOW!!! 👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

POST 요청을 날렸는데 ➡️ Created 201 응답이 오고 ➡️ Location 헤더에 해당 리소스의 아이디가 담겨오더라구요

정말 RESTful하다!라고 할 뻔 했으나...

**[Request Change]**
제가 이 API를 사용자라면 저 location 해더를 받아서 GET 요청을 날려서 생성된 정보를 받고 상세 페이지를 보여줄 것 같은데요.

@GetMapping("/reservations/{id}) 는 보이지 않네요...
혼란을 야기할 수 있는 것 같아요.

**[Comment]**
Location 헤더에 식별가능한 아이디를 담아서 보냈는데, 응답 바디에도 해당 정보를 담아서 보내주시는 이유가 있을까요?

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/controller/ReservationController.java
> +        }
**[Request Change]**

[디미터의 법칙](https://mangkyu.tistory.com/147)의 법칙을 적용해볼까요?

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/controller/ReservationController.java
> +    @ResponseBody
**[Comment]**

전 이 어노테이션 없어도 잘 돌아가던데, 굳이 달아주신 이유가 있을까요?

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/dto/Reservation.java
> +public class Reservation {
**[Comment]**

이 아이는 DTO 인가요?

그렇다면 Reservation에 대한 도메인 로직은 누가 관리할 수 있을까요?
만약 현재 시각보다 이전은 예약할 수 없다던지,
예약 시간을 변경한다던지,

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/dto/Reservation.java
> +    private String date;
**[Comment]**

Java에는 LocalDate와 같이 시간과 날짜를 나타내는 클래스들이 존재합니다.
그런 타입을 쓰지 않고 String 타입을 사용하신 이유가 있을까요?

String 타입으로 해당 값을 요청 받을 때 무엇이 우려되시나요?
만약 LocalDate를 필드로 가진 DTO로 @RequestBody를 받을 때, JSON이 잘 매핑 될까요?

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.noContent().build();
**[Comment]**

이전에 리뷰했던 금서님에게는 왜 이렇게 하셨는지 질문을 달았는데, 알고보니 이게 4단계 요구사항이더라구요..ㅎㅎ(머쓱)

이 명세에 동의 하시는 편인가요?
지우려고 했는데, 없으면 "오히려 좋아."이지 않을까요? 어떻게 생각하세요?

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/exception/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler(NotFoundReservationException.class)
**[Comment]**

import를 하지 않고 직접 위치를 작성하신 이유가 있을까요??

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/exception/ExceptionHandler.java
> +    }
**[Comment]**

만약에 @GetMapping("reservations/{id}")라는 API가 생긴다 했을 때, 그 메서드에서도 해당 Id의 reservation이 없으면 이 에러를 throw 하겠죠? 그럼 이곳에서 잡힐건데요.
400 BAD REQUEST가 적절하다고 생각하세요 404 NOT FOUND가 적절하다고 생각하세요?

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/exception/ExceptionHandler.java
> +public class ExceptionHandler {
**[Comment]**

ControllerAdvice와 RestControllerAdvice의 차이가 무엇이죠? 이곳에서 Rest...를 사용하신 이유를 말씀해주세요.

그리구 basePackage 속성도 공부해보시면 좋겠어요.

만약 이 어드바이스가 reservation 내에서만 사용하는 것이면 클래스 네이밍도 조금 명확하게 바꾸는게 좋겠어요.

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/exception/ExceptionHandler.java
> +    }
**[Request Change]**

이 어플리케이션에선 이 두가지 타입의 예외 말고는 절대 다른 예외가 터질 가능성이 없을까요?

제 생각엔 그렇지 않을 것 같아요. 해윤님도 동의하시나요? 그렇다면 예외가 터질까요? 그를 클라이언트에게 어떻게 알려줘야할까요?

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/exception/InvalidValueException.java
> +}
**[Comment]**

보통 java에서 입력값이 잘못됐을 때 터트리는 에러가 IlligalArgumentException을 던지는데요.
네이밍이 진짜 명확하죠? IlligalArgumentException에서 약간씩 워딩을 바꾸면 해윤님이 정의하신 커스텀 예외 네이밍과 같아지겠네요.

커스텀 예외를 사용하신 이유가 무엇일까요?
커스텀 예외를 사용하면 어떤 장점과 어떤 단점이 있다고 생각하세요?

2024-11-09 16:37 UTC, dooboocookie commented on src/test/java/roomescape/MissionStepTest.java
> +                .body("size()", is(3)); // 아직 생성 요청이 없으니 Controller에서 임의로 넣어준 Reservation 갯수 만큼 검증하거나 0개임을 확인하세요.
생성자에 데이터 세팅을 지웠으니 0으로 바꿔주죠

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/controller/ReservationController.java
> +    private AtomicLong index = new AtomicLong(1);
AtomicLong으로 동시성을 고려해서 아이디를 생성하는 것은 정말 멋진 방법이라고 생각해요!

해당 부분에 대해서 금서님과 동일해서 복붙한번 더 하겠습니다

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/controller/ReservationController.java
> +    private AtomicLong index = new AtomicLong(1);
### ReservationController의 역할

Reservation이라는 리소스에 접근은 이 Controller에서 밖에 못하게 해야할까요?
예를 들어, 만약 방탈출 관리자 기능 같은 새로운 API 가 만들어지면 어떻게 해야될까요?

#### 1.  MVC 패턴에서 Controller
- 이전 미션들에서 갖던 의미를 돌이켜보면 좋을 것 같아요.

#### 2. [레이어드 아키텍처](https://ksh-coding.tistory.com/92) 적용?
- 레이어드 아키텍처라는 개념을 알고 계실까요? 
- 간단하고 명확한 구조라서 프로젝트에 적용해보기 좋으실거에요. 
- 꼭 그 구조를 따라야하는 것은 아니고 한번 고민해보죠.

#### 3. `@Controller`의 의미
- Spring에서 Controller라는 Bean을 따로 명시한 이유가 뭘까요?
- 이것을 고민해보면서 저희가 Spring 같은 프레임워크를 사용했을 때 얻는 이점에 대해서 생각해보면 좋을 것 같아요.
- IoC, DI, AOP, ... 여러 이유가 있겠죠.
- 우리는 `방탈출 예약 서비스`를 만들기 위해 스프링을 사용한 것이죠. 스프링이 우선이 아리라는 말을 하고 싶은것인데요.
- 우리는 Spring이 망해도 `방탈출 예약 서비스`를 서비스해야하죠!
- 만약 Spring을 이 서비스에서 제거하고 다른 프레임워크로 바꾼다고 가정해보면 어떨까요?
  - 현실에서 일어날 가능성이 낮은 일이지만, 이런 고민을 해보는게 @Controller의 책임을 정의하는데에 도움이 될 것 같아요.


약간은 난해한 질문들을 드린 것 같아서 정리를 좀 해보자면,
이전 미션은 콘솔 어플리케이션이였는데, 웹 어플리케이션으로 변경한다고 생각하면 어떨까요?
일단 Controller를 제거하고 @Controller가 붙은 이런 컨트롤러를 붙이겠죠? 이런 상상을 해보죠

2024-11-09 16:37 UTC, dooboocookie commented on src/main/java/roomescape/controller/ReservationController.java
> +    private AtomicLong index = new AtomicLong(1);
### Reservation의 ID와 저장소

AtomicLong을 이용하여 ID를 부여한 것은 Reservation이 관리할 리소스(or 엔티티, or 레코드 ...)라는 의미겠죠?
지금은 메모리에 저장하고 있지만, 언젠가 RDB같은 곳에도 저장하게 될 수 있겠네요.
흠... 어제 스터디에서 JDBC 템플릿을  스터디한 것으로 알고 있는데요.

> 실제로 JDBC 템플릿을 적용해보거나, 
그를 적용한다고 했을 때  어떤 것이 필요할까요? 
그것이 현재 방식에서 비슷한 역할을 하고 있는 것은 누구일까요?

**[무시해도 되는 리뷰]**
Long을 사용하지 않고 AtomicLong을 사용한 것은 동시에 접근했을 때의 문제를 방지한 것으로 보이는데, 맞을까요?
그렇다면 AtomicLong만으로 충분할까요?🤔
ArrayList 정말 괜찮을까요?
정말 괜찮은지 테스트해볼까요?

2024-11-11 13:53 UTC, haeyoon1 commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
**1. reservationPage()**
getmapping으로 지정한 경로(localhost:8080/reservation)로 get요청을 받으면, resources>templates의 reservation.html파일을 찾아 사용자에게 보여줍니다.
**2. list()**
getmapping으로 지정한 경로(localhost:8080/reservations)로 get요청을 받으면, 
list형태의 reservations를 반환한다. Responsebody가 있기 때문에 뷰템플릿을 반환하지 않고, json형식의 데이터를 반환합니다.

2024-11-20 09:00 UTC, haeyoon1 commented on src/main/java/roomescape/controller/ReservationController.java
> +@Controller
> 혹시 Controller 어노테이션과 RestController 어노테이션의 차이를 알고 계신가요?

@controller는 view를 랜더링해주는 역할을 합니다.메서드의 리턴값이 "a"라면, template 패키지의 a.html파일을 찾아서 해당 html파일을 랜더링해줍니다. 
@RestController는 @controller + @responsebody 를 합친 어노테이션으로 메서드의 리턴값이 "a"라면 그 리턴값을 JSON형식으로 바꿔주어 텍스트로 a라고 화면에 보여줍니다!

> 이 컨트롤러에는 RestController는 사용하지 않으신 이유가 있으신가요?

홈화면을 보여주는 (/reservation) 메서드는 view화면을 랜더링해야하기 때문에 controller이라고 어노테이션을 작성했습니다!

2024-11-20 15:30 UTC, haeyoon1 commented on src/main/java/roomescape/controller/ReservationController.java
> +    @ResponseBody
아 view페이지를 랜더링하지 않아서 무작정 넣었는데 필요가 없었네요! ResponseEntity가 반환되는 객체를 HTTP 응답 본문에 자동으로 변환해주기 때문에 상관이 없다고 합니다!

2024-11-20 15:36 UTC, haeyoon1 commented on src/main/java/roomescape/dto/Reservation.java
> +public class Reservation {
Reservation에 대한 도메인 로직은 sevice 패키지에서 관리해야할 것 같습니다. 추가하도록 하겠습니다!

2024-11-20 15:55 UTC, haeyoon1 commented on src/main/java/roomescape/exception/ExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler(NotFoundReservationException.class)
insert하려고 누르면 저렇게만 작성되고 import문이 안나오더라고요 ... 해결방법있나요?

2024-11-26 06:28 UTC, merged