[Spring Core]송승현 미션제출합니다.
next-step/spring-roomescape-playground pull request #49
Opened 2023-12-16 13:35 UTC by tmdgus1715

## 구현 내용
Spring Core 10단계까지 구현 및 테스트 통과

## 질문 사항
각 계층에서 처리하는 예외에 대해 잘 모르겠어서 질문드립니다.
controller layer에서는 @Valid처럼 사용자의 입력 값에 대해 검증을 한다고 알고있는데,
검색 쿼리에서 반환되는 결과 값이 없을 때 발생하는 예외의 처리는 service layer에서 처리해야 하나요??(현재는 DAO에서 처리 중)

## 비고 
2단계 merge가 안되어서 files changed가 더럽습니다.. 양해부탁드립니다!

2023-12-22 12:32 UTC, Choi-JJunho requested changes
고생하셨습니다~
자잘한부분만 확인한번 부탁드려요!

2023-12-22 12:32 UTC, Choi-JJunho commented on src/main/java/roomescape/controller/ReservationController.java
>      @ResponseBody
ResponseEntity를 반환하고 있기 때문에 해당 어노테이션은 생략해도 될것같아요~

2023-12-22 12:32 UTC, Choi-JJunho commented on src/main/java/roomescape/controller/ReservationController.java
> +    @ResponseBody
> ResponseEntity를 반환하고 있기 때문에 해당 어노테이션은 생략해도 될것같아요~

같은 의견입니다~

2023-12-22 12:32 UTC, Choi-JJunho commented on src/main/java/roomescape/controller/TimeManagementController.java
> +    @ResponseBody
> ResponseEntity를 반환하고 있기 때문에 해당 어노테이션은 생략해도 될것같아요~

같은 의견입니다

2023-12-22 12:32 UTC, Choi-JJunho commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +                            "on r.time_id = t.id",
java 17에서는 큰따옴표 3개를 써서 multi-line String을 사용할 수 있습니다!

```java
// 예시
"""
query
description
"""
```
참고: https://www.baeldung.com/java-multiline-string

2023-12-22 12:32 UTC, Choi-JJunho commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +        params.addValue("time_id", newReservation.getTime().getId());
MapSqlParameterSource 👍

2023-12-22 12:32 UTC, Choi-JJunho commented on src/main/java/roomescape/service/TimeManagementService.java
> +        timeManagementRepository.deleteById(id);}
라인 포맷팅 한번 부탁드립니다!

2023-12-27 13:29 UTC, tmdgus1715 commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +                            "on r.time_id = t.id",
좋은 정보 고맙습니다!!

2023-12-27 13:43 UTC, tmdgus1715 commented
피드백 감사합니당~

2023-12-28 06:44 UTC, Choi-JJunho approved these changes
고생하셨습니다~! 👍

2023-12-28 06:54 UTC, merged