[Spring JDBC] 김선호 미션 제출합니다.
next-step/spring-roomescape-playground pull request #60
Opened 2024-01-13 05:32 UTC by SHKim55

# 2주차 미션(Spring JDBC)

예제 코드를 바탕으로 대부분의 코드를 작성하였습니다. 놓친 부분이나 개선해야 할 부분이 있다면 지적해주시면 감사하겠습니다.

## 학습 내용
- h2 DB 도입 및 기본 기능 이해
- DAO (DB 접근 로직을 분리한 객체 / MVC 중 'Model')
- 기본 DDL, DML (`CREATE TABLE`, `DROP TABLE`, `SELECT`, `INSERT`, `DELETE` 등)
- `RowMapper`, `KeyHolder`, `stream`
- `PreparedStatement`
- Spring에서 자동으로 생성되는 `JdbcTemplate`과 임의로 생성하는 `JdbcTemplate`의 차이점 (`Autowired` Annotation)
- `ResponseEntity.body()`를 통해 데이터 전달하기

## 코드 설명
- 이전에 만들었던 기본 CRUD 및 예외처리 코드들을 최대한 변경하지 않는 것을 목표로 함
- ReservationDAO 객체 생성 시 `JdbcTemplate` 및 `RowMapper` 자동 생성
- `INSERT`문 처리 시 DAO 객체 안에서 자동으로 `RowMapper` 및 `KeyHolder`를 활용하도록 설계
- ReservationController - 기존의 `ArrayList` 대신 ReservationDAO를 활용한 Controller 연동

## 질문사항
- 예제 코드는 DB 쿼리문을 한번에 모아서 작성하지 않고(Ex. CustomerDAO) 각각 QueryingDAO, UpdatingDAO로 기능적으로 분리하여 작성하였는데, 제가 개발한 방식과 비교했을 때 이러한 방식의 장단점이 각각 궁금합니다.
- 이전에 작성하였던 불필요한 코드들을 일단 주석으로 남겨두었는데 PR 전에 삭제해도 되는 지 궁금합니다.
- 현재 코드에서는 `SimpleJdbcInsert`를 사용하지 않았는데 나중에 문제가 되지 않는 지 궁금합니다.

2024-01-16 08:33 UTC, hong-sile requested changes
빠르게 짜주셨는데, 조금 리뷰가 늦었네요 ㅎㅎ

미션 요구사항은 잘 구현해주신 것 같아요.

몇몇 부분에 대한 코멘트를 남겼어요.
저희가 저번 스터디 할 때 요구사항 외에 피드백도 남겨달라 해서 약간의(?) 추가적인 피드백을 남겼답니다.

한번 확인해보시면 좋을 것 같아요.
(삽질 화이팅..!)

궁금한거 있으면 편하게 물어봐주세요!

2024-01-16 08:33 UTC, hong-sile commented on src/main/java/roomescape/ReservationDAO.java
> +    private final RowMapper<Reservation> reservationRowMapper = (resultSet, rowNum) -> {
RowMapper를 잘 이용해주셨군요!

2024-01-16 08:33 UTC, hong-sile commented on src/main/java/roomescape/ReservationController.java
> +        return ResponseEntity.ok().body(new ReservationDAO(jdbcTemplate).findAllReservations());
괄호안에 너무 많은 내용이 한번에 있어서 읽기 좀 힘든 것 같아요.

한번 분리해보는 건 어떨까요??

2024-01-16 08:33 UTC, hong-sile commented on src/main/java/roomescape/ReservationController.java
> +        return ResponseEntity.ok().body(new ReservationDAO(jdbcTemplate).findAllReservations());
ReserviationDao 객체를 조회할 떄마다 만들어 주는군요.

한 번만 ReservationDao를 만들고 이용하는 방법은 없을까요??

이 부분은 다음 시간에 배울 내용이긴 하지만, 한 번 스스로 찾아보는 것도 좋을 것 같아요.
(삽질 종용중...)

2024-01-16 08:33 UTC, hong-sile commented on src/main/java/roomescape/ReservationDAO.java
> +        jdbcTemplate.update(sql, Long.valueOf(id));
여기서 Long.valueOf로 감싸고 있군요?

굳이 감쌀필요는 없어요 오히려 더 많은 비용을 야기할 수 있답니다.

Java의 Wrapper 클래스와 primitve type에 대해 학습해보고, 댓글로 남겨주시겠어요?

2024-01-16 08:33 UTC, hong-sile commented on src/main/java/roomescape/ReservationController.java
> +//    주석처리 - 5단계 이전 코드
굳이 주석 처리 할필요 없이 지워도 괜찮아요!

지워주시면 좋을 것 같아요.

2024-01-16 08:33 UTC, hong-sile commented on src/main/java/roomescape/ReservationController.java
> +//            reservations.add(newReservation);
else 라인이 없어도 될 것 같아요.

throw를 하면 해당 함수의 아래라인은 무시된답니다??

2024-01-16 08:33 UTC, hong-sile commented on src/main/java/roomescape/ReservationController.java
> +        reservationDAO.insertNewReservation(newReservation);
이 경우엔 기존 데이터의 값이 변경되는 것이 아닌,

새로운 예약이 저장되기만 할 것 같아요.

어떤식으로 update 핸들러를 DAO를 이용해서 구현해볼 수 있을까요?

2024-01-16 08:33 UTC, hong-sile commented on src/main/java/roomescape/ReservationDAO.java
> +            PreparedStatement ps = connection.prepareStatement(sql, new String[]{"id"});
PreparedStatment와 keyholder를 잘 이용해주셨군요!! 좋습니다

2024-01-16 08:33 UTC, hong-sile commented on src/main/java/roomescape/ReservationDAO.java
> +            PreparedStatement ps = connection.prepareStatement(sql, new String[]{"id"});
preparedStatement를 쓸 때 파라미터를 (index와 value) 쌍 형태로 작성해주셨어요.

만약에 sql 쿼리를 잘못 작성해서 Date와 TIme을 거꾸로 쓴다거나,
새로운 칼럼이 생겨서 해당 메서드를 수정하다가 index를 잘 못 쓰는 경우가 생길 수도 있을 것 같아요.

preparedStatement에서 값을 세팅할 수 있는 다른 방법에 대해 한 번 알아보면 어떨까요?

2024-01-16 08:38 UTC, hong-sile commented
질문 주신부분에 대한 답을 남겨드릴게요.

Q. 예제 코드는 DB 쿼리문을 한번에 모아서 작성하지 않고(Ex. CustomerDAO) 각각 QueryingDAO, UpdatingDAO로 기능적으로 분리하여 작성하였는데, 제가 개발한 방식과 비교했을 때 이러한 방식의 장단점이 각각 궁금합니다.

명확한 답을 안 알려주고 싶긴 하지만, 지금 알기엔 조금 어려운 개념이니 넌지시 알려드리자면
1. 추후 DB에서 데이터를 읽는 것과 쓰는 것마다 부하의 차이가 있어서 성능적인 면에서 첫 번째인 것 같아요.(CQRS라는 키워드에 대해 한 번 찾아보세요 단, 깊게 들어가지 마세요 이건 진짜 지금 알 필욘 없습니다.)
2. 역할을 조금 더 명확하게 나눠 관리 또는 유지보수하기 수월함? -> 저는 이것도 조금 있는 것 같아요.

나머지는 한 번 스스로 고민해보고, 스스로 고민하고 찾아본 내용을 다음 스터디 때 이야기 해줘도 좋을 것 같아요.

2024-01-16 08:41 UTC, hong-sile commented
Q. 이전에 작성하였던 불필요한 코드들을 일단 주석으로 남겨두었는데 PR 전에 삭제해도 되는 지 궁금합니다.
지워주셔도 됩니다!! 이건 커밋에도 남겨뒀어용.

Q. 현재 코드에서는 SimpleJdbcInsert를 사용하지 않았는데 나중에 문제가 되지 않는 지 궁금합니다.
크게 문제가 되진 않아요. 왜 그런지는 한 번 찾아보는 건 어떨까요?
(윈도우에서 ctrl + b를 누르면 메서드 내부로 들어갈 수 있습니다.)

2024-01-18 05:18 UTC, SHKim55 commented on src/main/java/roomescape/ReservationController.java
> +//    주석처리 - 5단계 이전 코드
넵 삭제했습니다!

2024-01-18 05:18 UTC, SHKim55 commented on src/main/java/roomescape/ReservationDAO.java
> +        jdbcTemplate.update(sql, Long.valueOf(id));
Wrapper 클래스는 검색해보니 char, int, long 등의 primitive type을 객체로 활용할 수 있게 바꿔주는 일종의 외부 포장지와 같은 느낌을 주는 클래스인 것 같습니다. Wrapper로 감싸게 되면 안에 들어있는 값은 바꿀 수 없다고 하던데 말씀하신대로 어차피 id가 바뀔 일도 없고 매개변수로 이미 받아온 값이라 그대로 써도 될 것 같습니다.
(코드 수정: Long.valueOf(id)   ->  id)

2024-01-18 05:18 UTC, SHKim55 commented on src/main/java/roomescape/ReservationController.java
> +//            reservations.add(newReservation);
넵 수정했습니다~

2024-01-18 11:03 UTC, SHKim55 commented on src/main/java/roomescape/ReservationController.java
> +        return ResponseEntity.ok().body(new ReservationDAO(jdbcTemplate).findAllReservations());
ReservationDAO 객체의 중복 생성을 피하기 위해 Controller 객체 안의 private field로 변경했습니다.

2024-01-18 11:03 UTC, SHKim55 commented on src/main/java/roomescape/ReservationDAO.java
> +    private final RowMapper<Reservation> reservationRowMapper = (resultSet, rowNum) -> {
감사합니다!

2024-01-18 11:18 UTC, SHKim55 commented on src/main/java/roomescape/ReservationController.java
> +        reservationDAO.insertNewReservation(newReservation);
Update 요청 시 새로운 예약으로 바꾸지 않고 기존에 있던 예약 데이터를 수정할 수 있게 update-set SQL 문을 이용한 updateReservation 메서드를 DAO 안에 새로 만들었습니다. 테스트는 다 통과하는데 제가 맞게 개발한 지 잘 모르겠네요. 한 번 확인 부탁드립니다~

2024-01-18 14:37 UTC, hong-sile approved these changes
이번 미션 수고했어요 잘 구현해셨어요!

난이도나 리뷰는 어떠셨나요??

다음 스터디 때 리뷰방식이나 난이도, 미션에 대해서도 많이 피드백 해주세요!!

이번 미션은 이만 approve하겠습니다.

2024-01-18 14:37 UTC, hong-sile commented on src/main/java/roomescape/ReservationController.java
> +    @Autowired
좋아요! ReservationDao의 중복적인 생성을 막아주셨군요.

하지만, Autowired는 필요가 없답니다?

@Autowired가 무엇인지는 다음 스터디 때 알아볼게요!

2024-01-18 14:37 UTC, hong-sile commented on src/main/java/roomescape/ReservationDAO.java
> +            ps.setString(4, reservation.getId().toString());
setString으로 Long을 String으로 바꿔서 setting했군요.

ps.setLong도 있답니다?

2024-01-18 14:37 UTC, hong-sile commented on src/main/java/roomescape/ReservationDAO.java
> +        String sql = "UPDATE reservation SET name=?, date=?, time=? WHERE id=?";
쿼리가 적절하게 잘 바뀐 것 같네요!! 좋습니다

2024-01-18 14:37 UTC, hong-sile commented on src/main/java/roomescape/ReservationDAO.java
> +        jdbcTemplate.update(sql, Long.valueOf(id));
맞아요 Wrapper는 일종의 포장지이고, 불변값인 것도 맞습니다. 잘 공부하신 것 같군요.

primitive type일 때랑 Wrapper일 때랑 사용법이 조금씩 달라지니 알아두시면 좋을거에요

2024-01-18 14:37 UTC, hong-sile commented on src/main/java/roomescape/ReservationController.java
> +        reservationDAO.insertNewReservation(newReservation);
teast에서는 update에 대한 테스트가 없고, 버튼도 없으니 테스트하기 어려울 것 같긴 하네요.

하지만, intellij에서 http 요청을 보낼 수 있는 파일을 제공해 줄 수 있죠.

그 방법으로 테스트 해보시겠어요?(아니면, 테스트 코드를 짜보는 것도...?)

2024-01-19 02:42 UTC, byjo commented
@SHKim55 @hong-sile 
PR base 브랜치가 `main`으로 되어있어 변경했습니다.
다음 PR 작성 시 한 번 더 체크 부탁드려요 🙂
JDBC 미션 진행하고 리뷰하시느라 고생 하셨습니다! 다음 미션도 화이팅!

2024-01-19 02:42 UTC, merged

2024-01-19 10:00 UTC, SHKim55 commented on src/main/java/roomescape/ReservationDAO.java
> +            ps.setString(4, reservation.getId().toString());
엇 제가 못 찾았나봐요ㅋㅋ 알려주셔서 감사합니다~

2024-01-19 10:00 UTC, SHKim55 commented on src/main/java/roomescape/ReservationDAO.java
> +        String sql = "UPDATE reservation SET name=?, date=?, time=? WHERE id=?";
넵 감사합니다~

2024-01-19 10:02 UTC, SHKim55 commented on src/main/java/roomescape/ReservationController.java
> +    @Autowired
넵넵 감사합니다~