[Spring MVC] 이재빈 미션 제출합니다.
next-step/spring-roomescape-playground pull request #63
Opened 2024-01-13 13:30 UTC by jaebinGit

Spring MVC 미션 제출입니다!
README.md 파일에 요약있습니다.
리뷰 감사합니다!!

2024-01-15 07:43 UTC, hum02 requested changes
안녕하세요 재빈님~~ 😀
주말에 일정이 있어 리뷰가 조금 늦었네요 🤣
전반적으로 spring,java에 대해 어느정도 알고 미션 잘 수행해주셨다고 느꼈습니다.
approve해도 될 정도의 완성도라 생각하지만 궁금한 점도 있고 이야기 더 나눠보고 싶어 
request changes하겠습니다. 
질문에 답변만 해주셔도 되고 코드까지 수정하실 부분은 원하는 부분 반영해서 다시 요청해주세요!

2024-01-15 07:43 UTC, hum02 commented on src/main/java/roomescape/controller/ReservationController.java
> +
굿~~ stream을 활용해서 예외처리를 하셨군요! 이 부분은 재빈님이 저보다도 더 잘하신 것 같습니다.

2024-01-15 07:43 UTC, hum02 commented on src/main/java/roomescape/controller/ReservationController.java
> +                    .filter(it -> Objects.equals(it.getId(), id))
equals를 이용해서 필터링하셨군요! 흠 이부분은 저도 고민되는 것들이 있군요.
걸리는 부분은 getter를 통해 id를 가져온다는 점과, 꼭 objects.equals까지 사용해야 하나? 싶은 생각입니다. 

 우선 pathvariable부분은 Long이 아닌 long으로 가져왔다면 == 로도 비교가능할 것 같네요.
이 기회에 wrapper class는 어떤 차이가 있는지도 점검해보면 좋을 것 같습니다.

 그리고  getter로 값을 가져와서 검증하는 부분도 
아래처럼 reservation에 메서드를 만들어서 이를 사용할 수도 있는데 어떤 것이 나을지 
고민해보면 좋을 것 같습니다.

```java
    public boolean isEqualId(long id) {
        return this.id == id;
    }
```
객체의 메서드를 활용하는 게 아니라 값을 가져와서 사용한다면 '내가 객체를 객체스럽게 쓰고 있는게 맞나?' 생각해보는 것도 좋은 습관일 것 같아요!


  좀 더 오버를 해보자면 사실 지금 List<Reservation>를 일종의 저장소로 쓰고 있는데,
 저장소로부터 객체를 찾고 예외처리를 하는 책임을 별도의 객체로 넘기는 것도 생각해볼 수 있을 것 같아요! 일급컬렉션이란 키워드를 알아보시는 것도 좋겠군요.
Reservations 라는 클래스를 만들어 이 stream 로직을 해당 클래스에 위치시키면 컨트롤러는 더 순수하게 uri에 대한 매핑만을 수행할 수 있을 것 같습니다.

2024-01-15 07:43 UTC, hum02 commented on src/main/java/roomescape/Exception/BadRequestException.java
> +public class BadRequestException extends RuntimeException {
custom예외를 만드셨군요! custom예외를 사용할 때의 장단점이 무엇일까요?
재빈님은 어떤 장점을 기대하고 이를 사용하셨는지 궁금합니다!

2024-01-15 07:43 UTC, hum02 commented on src/main/java/roomescape/Exception/ExceptionController.java
> +    @ResponseStatus(org.springframework.http.HttpStatus.BAD_REQUEST)
responseEntity와 '@ResponseStatuc'를 둘 다 사용하셨군요!
둘 다 사용하신 이유가 있나요? 
ResponseEntity에서의 httpstatus 그대로 둔 채로 responseStatus에서의 httpStatus만 바꾼다면 둘 중 어떤 httpstatus를 반환하게 될지 궁금하군요.

2024-01-15 07:53 UTC, hum02 commented
readMe에서 mvc컴포넌트로 어떻게 더 잘 분리할까라는 물음에 대해서는
저는 mvc로 잘 분리한다는 게  사실  /view에 넘길 데이터 / 데이터를 생성하기 위한 로직 / 앞의 2개를 연결하는 controller
이렇게 나누는 거라 생각해요! 
즉 화면쪽에 넘길 데이터와 이 데이터를 생성하기 위한 비즈니스 규칙들을 어떻게든 잘 분리하면 mvc의 목적을 달성하는 게 아닌가 싶은데요...

이번 미션은 사실 controller의 사용 정도를 해보았을 뿐
 비즈니스 로직이랄 건 없어서 도메인에도 이를 위한 메서드가 없네요.
view와 model을 철저히 분리할 생각이셨다면 사실 controller에 데이터를 Reservation 도메인 자체로 받는게  아니라
 dto를 활용해야 했다고 봅니다.

2024-01-17 14:26 UTC, jaebinGit commented on src/main/java/roomescape/controller/ReservationController.java
> +        public String Reservation() {
좋은 의견 감사합니다!
좀 더 일관성 있는 코드가 될 것 같아요!

2024-01-17 14:31 UTC, jaebinGit commented on src/main/java/roomescape/controller/ReservationController.java
> +        public ResponseEntity<Void> deleteReservation(@PathVariable Long id) {
이런 방법이 있었군요..
반복되는 것을 줄일 수 있도록 RequestMapping을 사용하고, url 매핑을 위해 reservation을 사용하는 것을 위해 따로 PageController class도 만들었습니다!
한결 더 보기 편해진 것 같아요!
좋은 의견 감사합니다!!

2024-01-17 14:35 UTC, jaebinGit commented on src/main/java/roomescape/controller/ReservationController.java
> +        public ResponseEntity<List<Reservation>> readReservation() {
확장가능성을 고려한다면 readReservations가 좀 더 맞을 것 같네요!
좋은 의견 감사합니다 ㅎㅎ

2024-01-17 15:04 UTC, jaebinGit commented on src/main/java/roomescape/controller/ReservationController.java
> +            }
저도 이 부분을 고민했었는데, isBlank 메서드를 사용하니 훨씬 더 안정성 있는 것 같아요!
검증로직은 따로 Exception package에 추가하였어요!
또 ExceptionController도 Controller package로 이동했어요!
이렇게 보니 좀 더 가독성이 좋고, 단일 책임 원칙을 지킬 수 있는 것 같네요 ㅎㅎ
좋은 의견 감사합니다!

2024-01-17 15:05 UTC, jaebinGit commented on src/main/java/roomescape/controller/ReservationController.java
> +            Reservation member = reservations.stream()
제가 변수명을 안 바꿨었네요..
reservation으로 변경했습니다!

2024-01-17 16:39 UTC, jaebinGit commented on src/main/java/roomescape/Exception/BadRequestException.java
> +public class BadRequestException extends RuntimeException {
나중에 복잡한 상황에서의 예외처리를 대비하여 custom예외를 만들었습니다!
코드의 가독성 또한 향상될 것이라 기대됩니다.

2024-01-17 18:13 UTC, jaebinGit commented on src/main/java/roomescape/Exception/ExceptionController.java
> +    @ResponseStatus(org.springframework.http.HttpStatus.BAD_REQUEST)
@ResponseStatus를 미처 지우지 못 했네요!
오타라고 봐주시면 될 것 같습니다.

ResponseEntity에서의 httpstatus 그대로 둔 채로 responseStatus에서의 httpStatus만 바꾼다면 둘 중 어떤 httpstatus를 반환하게 될지 궁금하군요. -> ResponseEntity에 명시된 상태 코드가 우선적으로 적용된다고 합니다! 
ResponseEntity가 더 구체적으로(HTTP 응답의 상태 코드뿐만 아니라, 응답 본문(body), 헤더(headers) 등 HTTP 응답의 전체 구조) 반환하기 때문입니다.

2024-01-17 18:33 UTC, jaebinGit commented on src/main/java/roomescape/controller/ReservationController.java
> +                    .filter(it -> Objects.equals(it.getId(), id))
객체의 상황에 직접 접근하는 것보다는 객체가 제공하는 메서드를 사용하는 것이 더 낫겠군요. 
또 주어진 상황에서는 null값을 가지지 않는 primitive type인 long이 더 좋을 것 같아요!

객체를 객체스럽게 쓴다는 말이 와닿았네요..
좀 더 되돌아보면서 reservations라는 일급컬렉션을 만들어 좀 더 책임을 분명하게 해보았습니다!
좋은 의견 감사합니다!!

2024-01-17 19:02 UTC, jaebinGit commented on src/main/java/roomescape/controller/ReservationController.java
> +            Reservation newReservation = Reservation.toEntity(index.getAndIncrement(), reservation);
초록 스터디에서 제공하는 학습 테스트를 진행하다보니 toEntitiy를 사용하게 되었습니다!
스프링이 처음이다 보니 많이 참고하게 되더라구요..

정적 팩토리 메서드를 공부하다 보니, 저는 생성자의 접근 지정자를 public으로 설정하여 제가 본질적으로 사용한 것 같진 않다는 느낌이 드네요..

정적 팩토리 메서드의 장점은 명확한 의미 전달, 유연한 객체 생성(예를 들어 메서드 내부에서 반환하는 객체의 하위 클래스 인스턴스도 반환할 수 있다고 합니다), 캐싱과 재사용(항상 새로운 객체를 생성하지 않고, 기존에 생성된 객체를 재사용 -> 메모리 사용 최적화 및 성능 향상) 들이 있다고 합니다!
단점은 상속이 불가능한 것과 다른 개발자들이 정적 팩토리 메서드를 찾는 것이 어렵다고 합니다!
다음 사이트에서 보시면 좋을 것 같습니다. -> [https://hstory0208.tistory.com/entry/OOP-정적-팩토리-메서드를-왜-사용하는가-어떤-상황에-사용하는게-좋을까-생성자와-차이]

허나 다른 분의 코드를 리뷰하고 보니 컨트롤러에서 도매인 객체를 그대로 받는 것이 계층 간 경계를 모호하게 하거나, 도메인 객체가 변경될 때 문제가 될 수도 있겠단 생각을 했습니다.
따라서 DTO를 사용하여 데이터를 전달하는 것이 옳겠다는 생각을 하게 되었네요!

2024-01-17 20:38 UTC, jaebinGit commented
리뷰 반영하고, 추가적으로 학습한 사항 모두 반영했습니다!
좋은 리뷰 감사합니다 동흠님!

반영한 사항은
- @RequestMapping 이용 및 PageController 추가
- 검증로직 isBlank 메서드 이용
- ReservationDTO 생성 및 이용
- reservations class 추가 및 일급 컬렉션 사용
- 객체에 직접 접근하지 않도록 reservation class에 isEqualId 메서드 추가
- @ResponseStatus 삭제
- 인자명, 변수명, 메서드명 변경
- ExceptionController Controller package로 이동
입니다!

2024-01-18 07:07 UTC, hum02 commented on src/main/java/roomescape/controller/ReservationController.java
> +            Reservation newReservation = Reservation.toEntity(index.getAndIncrement(), reservation);
사실 지금 단계에서는 도메인과 dto의 필드도 같고, 도메인에 추가적인 비즈니스 로직이 없기 때문에 꼭 dto가 필요하진 않을 것 같아요!
dto를 사용할 수도 있다는 인지만 하셨다면 충분해보입니다.

2024-01-18 07:10 UTC, hum02 commented on src/main/java/roomescape/controller/ReservationController.java
> +                    .filter(it -> Objects.equals(it.getId(), id))
일급컬렉션을 활용해보셨군요!
지금 이 클래스가 가지고 있는 객체 저장의 책임이
db를 사용하게 된다면 어떻게 변할 지 보는 것도 재미있을 것 같습니다.

2024-01-18 07:16 UTC, hum02 commented on src/main/java/roomescape/Exception/BadRequestException.java
> +public class BadRequestException extends RuntimeException {
커스텀 예외로 더 여러 상황에 대해서 구체적인 예외 메시지를 넘기며 대응할 수 있는 건 맞다고 생각합니다.
하지만 그래도 직접 예외들을 정의해 관리해야 한다는 점, 그만큼 새로운 개발자가 오면 이것을 읽어봐야 알 수 있다는 점은 단점이 될 수도 있을 것 같군요.
커스텀 예외가 아닌 이미 존재하는 예외들도 생각보다 다양하게 여러 상황을 표현할 수 있고, 개발자라면 공통적으로 인지하고 있으니 또새로운 인력이라도 쉽게 읽을 수 있을 것 같아요.

정답은 없지만 이미 존재하는 여러 예외들에 대해서도 아신다면 좋을 것 같아서 해본 질문이었습니다!😄

2024-01-18 07:19 UTC, hum02 approved these changes
고생하셨습니다~ 
열정적으로 학습하시려는 게 느껴져서 좋았습니다!

2024-01-18 08:53 UTC, merged

2024-01-19 09:46 UTC, jaebinGit commented
> 고생하셨습니다~ 열정적으로 학습하시려는 게 느껴져서 좋았습니다! 잠은 충분히 주무시는 거겠죠...?

계절학기 일정과 휴가 일정이 겹쳐 무리했었네요 :)..
지금은 충분히 자고 있습니다! ㅎㅎ

이번 미션 고생하셨습니다!!