Step2
next-step/spring-roomescape-playground pull request #66
Opened 2024-01-14 09:40 UTC by polarpolar914

### 2주차 미션(Spring JDBC)

이전 코드와 학습테스트의 예제 코드를 바탕으로 작성했습니다. OOP나 클린코드 관련해서도 피드백 주실 부분이 있으시면 많은 피드백 부탁드립니다.
## 학습 내용

* h2 DB (in memory db 형태로도 사용가능)
* application.properties에 DB관련 설정하기(콘솔활성화, 콘솔과 디비 url 설정)
* Spring의 JDBC가 추상화된 부분과 JdbcTemplate 사용법
* ResponseEntity.ok().body()로 데이터를 전달하는 법
* keyHolder로 업데이트 된 entity의 PK값 가져오기
* rowMapper
## 코드 설명

* 이전 단계의 코드들은 필요하지 않을 경우 변경하지 않음
* ReservationUpdatingDAO와 ReservationQueryingDAO클래스를 만들고 JdbcTemplate객체를 생성자의 인자로 받음\
* SELECT처리 시 ReservationQueryingDAO에서 RowMapper를 사용
* INSERT처리 시 ReservationUpdatingDAO에서 KeyHolder를 사용
* ReservationController애서 List 대신 ReservationUpdatingDAO와 ReservationQueryingDAO를 사용

## 질문사항
* QueryingDAO, UpdatingDAO객체를 제가 짠 코드처럼 사용하는 것이 아니라 싱글톤패턴을 사용하는 것이 더 올바른 방식인지 궁금합니다. 
* 이전 단계의 코드들을 주석으로 남겨두는 것과 지우는 것 중 어느 쪽이 좋을지 궁금합니다.
* 학습테스트 코드에서 JdbcTemplate의 update메소드를 사용할 때 keyHolder를 사용할때만 람다함수와 PreparedStatement를 사용하고 keyHolder를 사용하지 않을때는 람다함수와 PreparedStatement를 사용하지 않은 이유가 궁금합니다.
* spring.h2.console.path=/h2-console는 application.properties에 추가안해도 디폴트값이 /h2-console인지 궁금합니다.

2024-01-16 09:49 UTC, hong-sile requested changes
코드를 읽고 몇몇 부분에 대한 리뷰를 남겼어요.

토론과 논쟁은 환영이기에, 제 의견에 반박해주셔도 좋습니다.
코드에 정답이란 건 존재하지 않거든요

리뷰 읽어보시고 모르는 것은 편하게 물어봐주세용

2024-01-16 09:49 UTC, hong-sile commented on src/main/java/roomescape/Reservation.java
> +    private final String name;
몇몇 필드에 final을 추가해주셨군요.
필드에 final을 추가해주신 이유가 있을까요?

2024-01-16 09:49 UTC, hong-sile commented on src/main/java/roomescape/ReservationQueryingDAO.java
> +        Reservation reservation = new Reservation(resultSet.getLong("id"), resultSet.getString("name"), resultSet.getString("date"), resultSet.getString("time"));
요 부분은 code style이 적용 안 된 것 같네용.

자동 포맷팅을 습관화합시다.
(인텔리제이 설정 중 저장하면 자동정렬되는 기능도 있다는데....)

2024-01-16 09:49 UTC, hong-sile commented on src/main/java/roomescape/ReservationUpdatingDAO.java
> +    private final RowMapper<Reservation> reservationRowMapper = (resultSet, rowNum) -> {
update할 때 RowMapper가 필요할까요?

어떨 때 RowMapper가 필요한 걸 까요?

2024-01-16 09:49 UTC, hong-sile commented on src/main/java/roomescape/ReservationUpdatingDAO.java
> +        jdbcTemplate.update(connection -> {
keyHolder와 preparedStatement를 잘 사용해주셨군요!

2024-01-16 09:49 UTC, hong-sile commented on src/main/java/roomescape/ReservationUpdatingDAO.java
> +        jdbcTemplate.update(connection -> {
PreparedStatement에 (index,value) 형태로 parameter들을 넣어줬군요.

index형태로 넣는 것은 변경 또는 작성에서 많은 실수를 유발할 수 있답니다.

어떤 실수가 발생할 수 있는지, 그리고 어떤 식으로 보완할 수 있는지 한번 찾아보시겠어요?

2024-01-16 09:49 UTC, hong-sile commented on src/main/java/roomescape/ReservationController.java
> +        ReservationUpdatingDAO reservationUpdatingDAO = new ReservationUpdatingDAO(jdbcTemplate);
ㅋㅋㅋㅋ 세마포어가 없어졌군요

2024-01-16 09:49 UTC, hong-sile commented on src/main/java/roomescape/ReservationController.java
> +        if (!exist) {
오 삭제하려는 reservation의 존재여부로 예외처리를 해주셨군요! 좋습니다.

2024-01-16 09:49 UTC, hong-sile commented on src/main/java/roomescape/ReservationController.java
> +        if (!exist) {
exist 여부로 Controller에서 실패 상태의 반환의 분기를 해주는군요.

직접적으로 분기해주는 것도 좋지만, '예외처리'라는 상황은 Exception으로 명시적으로 표현해주는 건 어떨까요?

그리고, 유지보수관점에서 단순하게 예외가 발생하면 클라이언트에게 응답만 에러코드에 맞게 내려주면 될까요?
어떤 방법이 있을까요?

2024-01-16 09:49 UTC, hong-sile commented on src/main/java/roomescape/ReservationUpdatingDAO.java
> +        String sql = "SELECT COUNT(*) FROM reservation WHERE id = ?";
존재하는 지에 대한 여부를 파악하기 위해 select로 먼저 확인하는군요.

예외상황에 대해 빠르게 확인할 수 있어서 이렇게 짜신 것 같아요

단, 성공의 경우에 쿼리가 디비에 두번 날라가는 군요.
디비에 쿼리를 날리는 작업은 백엔드 작업중 많은 리소스를 소모하는 작업입니다.

작은 규모의 어플리케이션에선 상관 없지만, 규모가 커지면 문제가 될 수도 있어요.
(사실 진짜론 실제론 나갈 쿼리가 하나에서 두 개가 됐다고 해서 큰 문제가 되진 않긴 합니당.)

2024-01-16 09:49 UTC, hong-sile commented on src/main/java/roomescape/ReservationUpdatingDAO.java
> +        String sql = "SELECT COUNT(*) FROM reservation WHERE id = ?";
어떻게 하면 쿼리를 한 번 날리면서, 실제 쿼리가 정상동작했는지를 알 수 있을까요?

hint : jdbcTemplate.update의 반환값을 이용해본다면???

2024-01-16 09:52 UTC, hong-sile commented on src/main/java/roomescape/ReservationController.java
> +        ReservationUpdatingDAO reservationUpdatingDAO = new ReservationUpdatingDAO(jdbcTemplate);
현재 reservationDao를 이용하는 모든 곳에서, 요청마다 ReservationDao를 생성해주고 있어요.

어떻게 하면, 이러한 객체 생성 소멸을 줄일 수있을까요?

(다음 장에서 배울 내용이긴 하지만 한 번 스스로 삽질(?)해서 알아봐보시죠!)

2024-01-16 09:53 UTC, hong-sile commented
이전 PR을 머지하긴 했지만 몇몇 리뷰가 남아있답니다.

적용을 해주셔도 좋고, 적용하지 않을거라면 그렇게 생각한 이유를 남겨주세요
https://github.com/next-step/spring-roomescape-playground/pull/53

2024-01-16 09:59 UTC, hong-sile commented
Q. QueryingDAO, UpdatingDAO객체를 제가 짠 코드처럼 사용하는 것이 아니라 싱글톤패턴을 사용하는 것이 더 올바른 방식인지 궁금합니다.

싱글톤 패턴을 떠올리셨군요!! 좋습니다.
지금 Dao 객체가 요청마다 생성-소멸 사이클을 반복하고 있어서 불필요한 오버헤드가 있긴 해요.
이 부분에 대해서는 한 번 생각하신바를 적용해보시죠

Q. 이전 단계의 코드들을 주석으로 남겨두는 것과 지우는 것 중 어느 쪽이 좋을지 궁금합니다.
지워주셔도 좋습니다! 저희가 최종적으로 목표하는 것은 어플리케이션을 완성하는거니까요!
(과거코드를 보고싶으면 커밋을 봐도 되니까요)

Q. 학습테스트 코드에서 JdbcTemplate의 update메소드를 사용할 때 keyHolder를 사용할때만 람다함수와 PreparedStatement를 사용하고 keyHolder를 사용하지 않을때는 람다함수와 PreparedStatement를 사용하지 않은 이유가 궁금합니다.

학습테스트 코드에선 단순히 사용법을 보여주기 위한 용도지 best practice를 모아둔 것은 아니긴 합니다.
delete나, select에서도 preparedStatement를 활용할 수도 있어요.
음, keyHolder는 왜 다른 메서드에선 안 쓰였을까요? 이건 한번 생각해보시겠어요.

Q. spring.h2.console.path=/h2-console는 application.properties에 추가 안 해도 디폴트값이 /h2-console인지 궁금합니다.
[spring 공식문서](https://docs.spring.io/spring-boot/docs/1.3.1.RELEASE/reference/html/boot-features-sql.html#boot-features-sql-h2-console-custom-path) 에는 그냥 설정했다고 나와있습니다.
이런 경로 같은 것들은 어쩔때는 이유가 없기도 해요

2024-01-16 12:00 UTC, hong-sile commented on src/main/java/roomescape/ReservationUpdatingDAO.java
> +    private final RowMapper<Reservation> reservationRowMapper = (resultSet, rowNum) -> {
추가적으로 RowMapper는 어떤 식으로 동작하는 걸까요?
(이거는 굳이 안 파셔도 됩니다. 하지만 파면 개인적으로 좋은 것 같아요.)

2024-01-17 08:41 UTC, Choi-JY1107 commented on src/main/java/roomescape/ReservationQueryingDAO.java
> +        Reservation reservation = new Reservation(resultSet.getLong("id"), resultSet.getString("name"), resultSet.getString("date"), resultSet.getString("time"));
`ctrl` + `alt` + `L` 입니다!

2024-01-17 12:11 UTC, polarpolar914 commented on src/main/java/roomescape/Reservation.java
> +    private final String name;
일단 이번 과제에서는 Reservation.java를 수정한 기억이 없네요...
final키워드를 지워보니 intellij가 노란줄을 띄우며 Field 'name' may be final이라고 하는 걸 보니 아마 import를 위해 option+enter를 누를때 final키워드도 생긴 건 아닐까 생각해봅니다.

제 생각에는 intellij는 동시성문제나 잘못된 로직으로 데이터가 변하는 등의 문제를 방지하기위해 final키워드를 쓰는것을 추천한 것같습니다.

final키워드를 의도적으로 추가한 것은 아니지만 현재까지는 과제에서 삽입, 삭제, 조회는 있으나 수정이 없으므로 앞으로 수정기능을 구현할 생각이 없다면 final키워드를 사용하는 것이 이점이 많을 것 같습니다.

다만 동시성문제나 잘못된 로직으로 데이터가 변하는 등의 문제를 방지하기위해 final키워드를 쓰는것이라면 몇몇 필드가 아닌 모든 필드에 final키워드를 추가하는게 좋을것 것 같네요.

2024-01-17 12:29 UTC, polarpolar914 commented on src/main/java/roomescape/ReservationQueryingDAO.java
> +        Reservation reservation = new Reservation(resultSet.getLong("id"), resultSet.getString("name"), resultSet.getString("date"), resultSet.getString("time"));
자동포메팅을 한다고 했는데... 우테코 스타일 xml이 적용이 안되어있었네요... 죄송합니다.

2024-01-17 12:54 UTC, polarpolar914 commented on src/main/java/roomescape/ReservationController.java
> +        ReservationUpdatingDAO reservationUpdatingDAO = new ReservationUpdatingDAO(jdbcTemplate);
네... keyholder를 쓰면서 지웠습니다.

그리고 keyholder를 사용하면 키를 spring단에서 생성하는 것이 아니라 DB가 생성하므로 DB가 키값 생성과 관련된 동시성 문제는 해결해주는지와 keyHolder를 쓰면 PK관련 동시성 문제는 신경쓰지않아도 되는지도 궁금합니다.

2024-01-17 21:15 UTC, polarpolar914 commented on src/main/java/roomescape/ReservationUpdatingDAO.java
> +        String sql = "SELECT COUNT(*) FROM reservation WHERE id = ?";
jdbcTemplate.update의 반환값이 몇 개의 데이터 레코드가 수정되었는지를 나타내는 것 을 이용하여 delete쿼리 한번만을 날리도록 수정하였습니다.

2024-01-18 15:39 UTC, polarpolar914 commented on src/main/java/roomescape/ReservationController.java
> +        if (!exist) {
DAO클래스에서 아래와 같이 Exception으로 표현해보았습니다. 유지보수관점에서 에러코드 말고 오류 로그를 남기는 등의 작업을 할 수 있을것같은데 아직은 무엇을 할 수 있을지 감이 안오네요...
```
public boolean delete(Long id) {
        String sql = "DELETE FROM reservation WHERE id = ?";
        int num = jdbcTemplate.update(sql, id);
        if (num == 0) { // 삭제할 대상이 없는 경우
            handleNotFoundReservationException(new NotFoundReservationException("Reservation is not found in DB with id: " + id));
            return false;
        }
        return true;
    }

    @ExceptionHandler(NotFoundReservationException.class)
    public ResponseEntity handleNotFoundReservationException(NotFoundReservationException e) {
        return ResponseEntity.badRequest().build();
    }
```

2024-01-18 15:39 UTC, polarpolar914 commented on src/main/java/roomescape/ReservationUpdatingDAO.java
> +    private final RowMapper<Reservation> reservationRowMapper = (resultSet, rowNum) -> {
db에 쿼리를 날리고 받은 결과를 자바의 객체에 매핑하기 위해 RowMapper가 필요한 것 같습니다. 
따라서 select 쿼리가 아니라 update나 delete에서는 필요하지 않을 것 같습니다.

RowMapper는 어떤 식으로 동작하는 지는 다음에 한번 파보겠습니다.

2024-01-22 05:21 UTC, merged