[Spring MVC] 함성준 미션 제출합니다.
next-step/spring-roomescape-playground pull request #67
Opened 2024-01-15 21:47 UTC by hamseongjun

안녕하세요! 개인 사정도 있었는데, 스프링이 처음인지라 많이 어려워 학습이 늦어지는 바람에 예정보다 더 늦었네요... 죄송합니다.

리뷰 잘 부탁드립니다!
중간 중간 커밋하지 않고, 한 번에 커밋을 했는데 다음 번에는 보기 편하도록 나눠서 커밋하겠습니다.

3번, 4번 단계였던 추가, 삭제, 그리고 예외 처리에 대한 개념 숙지가 많이 미흡한 상태에서 작성한 것이라 제가 잘 작성한 것이 맞는지, 개선할 곳이 있는지 살펴봐주시면 감사하겠습니다..!

2024-01-16 15:54 UTC, kwonyj1022 requested changes
안녕하세요! 미션 구현하시느라 수고하셨습니다~
성준님과 이야기해보고 싶은 부분 위주로 리뷰 남겼습니다.

2024-01-16 15:54 UTC, kwonyj1022 commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
만약 get 요청에 대한 api가 아래와 같이 변경되면 어떻게 할까요?
```json
[
    {
        "id": 1,
        "name": "브라운",
        "year": "2023",
        "hour": "01",
        "day": "01",
        "time": "10:00"
    },
    {
        "id": 2,
        "name": "브라운",
        "year": "2023",
        "hour": "01",
        "day": "02",
        "time": "11:00"
    }
]

2024-01-16 15:54 UTC, kwonyj1022 commented on src/main/java/roomescape/controller/ReservationController.java
> +                .body(newReservation);
별 거 아니긴 한데 한 줄에 점 하나씩 허용해서 아래처럼 많이 작성하는 것 같아요
```suggestion
        return ResponseEntity.created(URI.create("/reservations/" + newReservation.getId()))
                             .body(newReservation);
```

2024-01-16 15:54 UTC, kwonyj1022 commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
예외 처리도 같은 컨트롤러에 두신 이유가 무엇인가요~?

2024-01-16 15:54 UTC, kwonyj1022 commented on src/main/java/roomescape/exception/InvalidReservationException.java
> +    }
상속을 사용해서 구현해 주셨군요! 👍

2024-01-16 15:54 UTC, kwonyj1022 commented on src/main/java/roomescape/model/Reservation.java
> +    }
빈 생성자는 어디에 사용되나요?

2024-01-16 15:54 UTC, kwonyj1022 commented on src/main/java/roomescape/model/Reservation.java
> +    }
이 생성자의 접근지정자는 default군요! 이렇게 하신 이유가 무엇인가요?

2024-01-16 15:54 UTC, kwonyj1022 commented on src/main/java/roomescape/model/Reservation.java
> +    }
이 메서드는 사용하지 않는 것 같은데 작성하신 이유가 무엇인가요? 의도가 궁금하네용

2024-01-16 15:54 UTC, kwonyj1022 commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
NotFoundReservationException은 예외메시지를 포함하고 있는데, 정작 예외 처리에서는 해당 예외메시지를 어떤 방식으로도 개발자와 사용자에게 보여주지 않고 있는 것 같아요. 개발자나 사용자에게 예외메시지를 보여주지 않으면 어떤 예외가 왜 발생했는지 인지하기 어려울 것 같은데 어떻게 해결할 수 있을까요?

2024-01-16 15:54 UTC, kwonyj1022 commented on src/test/java/roomescape/MissionStepTest.java
> +    void 이단계() {
다른 개발자가 이 테스트 코드를 보면 어떤 기능을 테스트하는지 한눈에 알기 힘들 것 같아요. 지금은 테스트 개수가 몇 개 안 되지만 테스트가 500개 1000개 넘어간다면 일일이 테스트코드를 다 읽어보면서 파악하기는 힘들 것 같아요. 어떻게 해결할 수 있을까요?

2024-01-17 02:37 UTC, hamseongjun commented on src/main/java/roomescape/controller/ReservationController.java
> +                .body(newReservation);
아하, 코드 습관 교정 감사합니다!!

2024-01-17 02:44 UTC, hamseongjun commented on src/test/java/roomescape/MissionStepTest.java
> +    void 이단계() {
테스트 코드를 지금처럼 하나의 파일에서 모두 처리하지 않고, 
기능별로 분리하거나 이번 미션처럼 단계 별로 명시된 프로세스가 있다면 단계 별로 나누는 것이 좋을 것 같아요. 
주석도 달면 좋구요!

2024-01-17 02:54 UTC, hamseongjun commented on src/main/java/roomescape/model/Reservation.java
> +    }
학습 테스트 - MVC(2)에서 @PostMapping을 처리할 때, toEntity 메소드를 이용하여 새 객체를 만들더라구요.
해당 코드를 참고해서 미션을 진행하다가 이 코드의 의미를 모르겠어서 그냥 new로 객체를 생성하는 코드로 수정했습니다. 수정 후에 필요 없어진 이 코드를 삭제하는 것을 깜빡했네요..
혹시, 학습 테스트에서 메소드를 해당 메소드를 사용한 이유가 무엇인지 알고 계신가요?

2024-01-17 03:05 UTC, hamseongjun commented on src/main/java/roomescape/model/Reservation.java
> +    }
무조건적인 접근을 경계하다 보니 제가 디폴트로 접근 지정자를 작성하는 습관이 있는 것 같습니다. 후에 public으로 변경해야 하는 상황이 오면 그 때 수정하는 편이에요. 혹시 안 좋은 습관일까요?

2024-01-17 03:19 UTC, hamseongjun commented on src/main/java/roomescape/model/Reservation.java
> +    }
학습 테스트 코드에도 빈 생성자가 사용되지 않지만, 정의되어 있어서 "원래 그냥 적어두는 것이 좋은 건가?" 라고 생각하고, 가볍게 넘어갔던 것 같습니다.  
빈 생성자의 역할이 없다면, 불필요한 코드를 삭제하고, 자바에서 제공하는 자동 생성자를 사용하는 것이 개인적으로 맞다고 생각하는데, 예진님의 생각은 어떠하신가요?

2024-01-17 03:24 UTC, hamseongjun commented on src/test/java/roomescape/MissionStepTest.java
> +    void 이단계() {
테스트 코드를 지금처럼 하나의 파일에서 모두 처리하지 않고, 
기능, 모듈별로 분리하거나 이번 미션처럼 단계 별로 명시된 프로세스가 있다면 단계 별로 나누는 것이 좋을 것 같아요. 
주석도 달면 좋구요!

2024-01-17 03:25 UTC, hamseongjun commented on src/main/java/roomescape/model/Reservation.java
> +    }
학습 테스트 코드에도 빈 생성자가 사용되지 않지만, 정의되어 있어서 "원래 그냥 적어두는 것이 좋은 건가?" 라고 생각하고, 가볍게 넘어갔던 것 같습니다.
빈 생성자의 역할이 없다면, 불필요한 코드를 삭제하고, 자바에서 제공하는 자동 생성자를 사용하는 것이 개인적으로 맞다고 생각하는데, 예진님의 생각은 어떠하신가요?

2024-01-17 03:25 UTC, hamseongjun commented on src/main/java/roomescape/model/Reservation.java
> +    }
무조건적인 접근을 경계하다 보니 제가 디폴트로 접근 지정자를 작성하는 습관이 있는 것 같습니다. 후에 public으로 변경해야 하는 상황이 오면 그 때 수정하는 편이에요. 혹시 안 좋은 습관일까요?

2024-01-17 03:26 UTC, hamseongjun commented on src/main/java/roomescape/model/Reservation.java
> +    }
학습 테스트 - MVC(2)에서 @PostMapping을 처리할 때, toEntity 메소드를 이용하여 새 객체를 만들더라구요.
해당 코드를 참고해서 미션을 진행하다가 이 코드의 의미를 모르겠어서 그냥 new로 객체를 생성하는 코드로 수정했습니다. 수정 후에 필요 없어진 이 코드를 삭제하는 것을 깜빡했네요..
혹시, 학습 테스트에서 메소드를 해당 메소드를 사용한 이유가 무엇인지 알고 계신가요?

2024-01-17 03:31 UTC, hamseongjun commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
예외 처리가 간단한 편이라 따로 파일을 만들어서 관리하는 것은 오히려 번거로울 것 같아서 깊이 생각하지 않고 이곳에 두었습니다. 
예외 처리도 컨트롤러에 두지 않고 따로 분리하는 것이 좋은 건가요?

2024-01-17 05:38 UTC, hamseongjun commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
return ResponseEntity.badRequest().build(); 코드에서 build 대신 body(e.getMessage()); 로 바꾸면 될 것 같습니다..
만 이렇게 한다고 하여 개발자에게 오류 메시지가 표시되는지는 잘 모르겠습니다.

2024-01-17 06:16 UTC, hamseongjun commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
Reservation 파일의 멤버를 수정할 것 같습니다. 예진님이 바라시는 답이 있으신가요?

2024-01-17 06:18 UTC, hamseongjun commented
꼼꼼하게 리뷰해주셔서 정말 감사합니다. 예진님 덕분에 질문들에 대해 답을 생각해보고 공부하는 과정에서 많은 것을 배울 수 있었어요😊

2024-01-17 12:12 UTC, kwonyj1022 commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
Reservation 도메인이 api가 변동될 때마다 바뀌는 건 적절하지 않은 것 같다고 생각해요.
api 중 "name"이라는 key가 "nickname"으로 바뀌었을 때 Reservation의 변수명을 수정하면 Reservation에 있는 getName() 메서드도 `return name;`에서 `return nickname;`으로 바뀌어야 하고 메서드명도 바꾸게 될 수도 있어요. 또 단순 getter뿐만 아니라 name이라는 필드를 참조하는 모든 메서드를 수정해야 할 것 같아요. 단순히 api가 바뀌었을 뿐인데 말이죠.

그래서 응답에만 사용할 dto를 만드는 것은 어떤지 건의드립니다! 

또한 응답 api 뿐만 아니라 요청 api도 충분히 변동 가능성이 있기 때문에 post 요청 시에도 Reservation 도메인을 사용하는 것보다 request 전용 dto를 만드는 것은 어떤가요?

2024-01-17 12:15 UTC, kwonyj1022 commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
지금의 설계대로라면 지금은 ReservationController만 있지만 다른 여러 Controller가 있을 때, 각 controller마다 예외처리를 나눠서 관리하게되면, 나중에 어떤 특정 예외에 대한 처리를 수정하고 싶을 때 찾기 어려울 것 같아서 저는 별도로 관리하는 편입니다. 물론 정답은 없으니 성준님이 더 좋다고 생각하는 방법대로 하면 될 것 같아요!

2024-01-17 12:17 UTC, kwonyj1022 commented on src/main/java/roomescape/model/Reservation.java
> +    }
특별한 의도가 없는 빈생성자가 존재한다면, 완전하지 않은 객체가 생성될 가능성이 있기 때문에 저는 선호하지 않는 편이에요. 각 필드가 null로 할당된 객체가 프로그램 내에 돌아다니게 되면 어떤 예상치 못한 버그가 발생할지 알 수 없으니까요! 물론 지금은 규모가 작아서 디버깅이 쉬울 수 있겠지만 협업하는 상황이나 사이즈가 큰 프로젝트에서는 위험성이 큰 것 같아요!

2024-01-17 12:18 UTC, kwonyj1022 commented on src/main/java/roomescape/model/Reservation.java
> +    }
좋은 것 같아요! 저도 접근 범위를 작게 가져갈 수 있다면 그렇게 하는 편이 좋다고 생각합니당

2024-01-17 12:24 UTC, kwonyj1022 commented on src/main/java/roomescape/model/Reservation.java
> +    }
"정적팩토리메서드" 키워드로 학습해 보시는 것을 추천합니다! 😀

2024-01-17 12:27 UTC, kwonyj1022 commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
body에 담는 것은 사용자에게 보이게 될 거에요~ 개발자도구를 통해 보거나 프론트엔드 개발자가 해당 예외메시지를 사용자가 볼 수 있도록 가공해주거나 하면요!
개발자를 위해서는 Logger를 사용해서 로그를 남기는 방법도 있답니당

2024-01-17 12:29 UTC, kwonyj1022 commented on src/test/java/roomescape/MissionStepTest.java
> +    void 이단계() {
좋아요! 또 주석도 좋지만 `@DisplayName` 어노테이션을 사용하면 아래 사진처럼 테스트 실행 결과에서 설명을 확인할 수 있어서 더 편리해요
![image](https://github.com/next-step/spring-roomescape-playground/assets/96688810/b9399d5c-0823-45cc-8b26-d2c0299e114e)

2024-01-18 09:24 UTC, hamseongjun commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
듣고 보니 예진님의 생각이 맞는 것 같습니다.
응답과 요청 두 개의 dto를 한 번 구현해보겠습니다!

2024-01-18 09:32 UTC, hamseongjun commented on src/main/java/roomescape/model/Reservation.java
> +    }
아하 그렇겠네요..! 감사합니다!!

2024-01-18 09:34 UTC, hamseongjun commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
아하 로그를 남기는 방법도 있군요! 감사합니다 :)

2024-01-18 09:39 UTC, hamseongjun commented on src/test/java/roomescape/MissionStepTest.java
> +    void 이단계() {
오호 굉장히 유용한 어노테이션이네요~! 혼자 코딩할 때는 테스트 코드를 작성하지 않는 편이라 Junit에 대해서 잘 몰랐는데, 이번 기회에 학습해봐야겠어요 감사합니다!! 🥰

2024-01-19 10:57 UTC, kwonyj1022 approved these changes
피드백은 다음 미션에서 반영해주세요! 수고하셨습니다~

2024-01-21 07:02 UTC, merged