[Spring Core] 김도형 미션 제출합니다.
next-step/spring-roomescape-playground pull request #87
Opened 2024-02-02 09:43 UTC by pdohyung

안녕하세요. Core 미션 제출입니다.
리뷰 잘 부탁드립니다. 😊

같이 논의해 볼 사항이나 질문이 있다면 편하게 남겨주세요 !

2024-02-05 03:15 UTC, leejongsuu commented
안녕하세요 도형님 코드 잘 봤습니다 !
혹시 이번 미션 제외하고도 궁금하신게 있으시다면 남겨주세요!
고생하셨습니다 !

2024-02-05 03:16 UTC, leejongsuu requested changes
안녕하세요 도형님 코드 잘 봤습니다 !
혹시 이번 미션 제외하고도 궁금하신게 있으시다면 남겨주세요!
고생하셨습니다 !

2024-02-05 03:16 UTC, leejongsuu commented on src/main/java/roomescape/domain/time/service/TimeService.java
> +@Service
@Service 에노테이션은 @Component 에노테이션과 별 차이가 없는데요
굳이 @Service 에노테이션을 붙여주신 이유가 있을까요?
또,  현재 service레이어는 레퍼지토리와 컨트롤러 간의 dto, entity변환 역할만 하는 것 같은데요!
서비스 레이어의 역할이 무엇이 더 있을지 생각해보시면 좋을 것 같아요!

2024-02-05 03:22 UTC, leejongsuu requested changes

2024-02-05 03:22 UTC, leejongsuu commented on src/main/java/roomescape/domain/time/repository/TimeDao.java
> +}
만약 Time을 삭제하려고하는데 Reservation이 삭제하려는 Time을 참조하고 있으면 어떻게 될까요?

2024-02-05 10:16 UTC, pdohyung commented on src/main/java/roomescape/domain/time/repository/TimeDao.java
> +}
이 부분 같은 경우는 cascade 설정이 필요하다고 생각했지만 요구사항에는 없는 거 같아서 적용하진 않았습니다.
종수님은 어떻게 처리하셨나요 ?

2024-02-05 10:16 UTC, pdohyung commented on src/main/java/roomescape/domain/time/service/TimeService.java
> +@Service
`@Transactional`을 통해 작업을 단위로 분리해서 관리하는 역할이 있겠네요.
당시에는 복잡한 로직이 없어서 미처 생각을 못 했습니다.
피드백 감사합니다. 👍

2024-02-05 10:16 UTC, pdohyung commented on src/main/java/roomescape/domain/time/service/TimeService.java
> +                .orElseThrow(() -> new BusinessException(TIME_NOT_FOUND));
> 만약 Time 테이블의 데이터가 양이 많으면 불필요한 조회들이 많을 것 같은데 어떻게 생각하시나요?

원래는 findTimeById 메서드로 time이 존재하지 않으면 예외 처리를 하도록 적용했습니다.
그런데 당시에는 쿼리가 동작하면 오류가 발생하여, 일단 findAllTimes 메서드로 처리를 했습니다.
현재는 수정해서  findTimeById 메서드로 적용해놨습니다.

> 또, 이 경우 findAllTimes, deleteTimeById 쿼리가 2번 날라가게 되는데 1번으로 줄일 순 없을까요?

존재하지 않는 시간을 삭제하는 경우, 예외 처리를 해야 합니다.
그래서 deleteTimeById는 데이터를 삭제하는 역할만 하고 예외 처리는 findTimeById를 사용했습니다.
당시에는 더 좋은 방법이 떠오르지 않았는데 jdbc의 메서드를 활용하면 더 나은 방법도 있을 것 같네요.
종수님은 어떻게 생각하시나요 ?

2024-02-06 03:13 UTC, leejongsuu commented on src/main/java/roomescape/domain/time/service/TimeService.java
> +                .orElseThrow(() -> new BusinessException(TIME_NOT_FOUND));
```
public void deleteTimeById(Long id) {
        String sql = "DELETE FROM time WHERE id = ?";
        jdbcTemplate.update(sql, id);
    }
```
에서 `jdbcTemplate.update(sql, id);`의 반환 값이 무엇인지 생각해보시면 좋을 것 같아요!

2024-02-06 03:17 UTC, leejongsuu commented on src/main/java/roomescape/domain/time/repository/TimeDao.java
> +}
저도  `DataIntegrityViolationException` 예외 처리 이외의 따로 다른 작업은 하지 않았는데요,
도형님께서 놓치신 부분이진 않을까 궁금해서 여쭤봤습니다!
cascade도 좋은 방법인 것 같아요!

2024-02-08 12:57 UTC, leejongsuu approved these changes

2024-02-09 01:13 UTC, merged