[Spring MVC] 김보배 미션 제출합니다.
next-step/spring-roomescape-playground pull request #98
Opened 2024-02-03 12:48 UTC by Kimbobae1

스프링을 처음해보다보니 오류도 많이 생겼고 새로 공부할 것도 굉장히 많았습니다..!
어노테이션들도 전부 처음보는 것들이어서 계속 공부해야겠습니다..

2024-02-04 02:57 UTC, juntae6942 requested changes
전반적으로 잘 짜신 것 같아요! 편리한 annotation 에 대해서도 같이 공부해보면 좋을 것 같아요. Reservation부분에 쓰신 getter, setter도 annotation하나로 해결할 수 있거든요!

2024-02-04 02:57 UTC, juntae6942 commented on src/main/java/roomescape/controller/ReservationController.java
> +
저도 이부분 처음에는 이렇게 했었는데, 스프링 프레임 워크의 기본 welcome page인식에 대해서 알아보면 좋을 것 같아요. 따로 코드 작성 없이도 이 부분을 할 수 있거든요 파일이름을 수정하는 방법으로요

2024-02-04 02:57 UTC, juntae6942 commented on src/main/java/roomescape/controller/ReservationController.java
> +
저는 ResponseEntity로 감싸는 생각 못했는데 좋은 것 같아요!

2024-02-04 02:57 UTC, juntae6942 commented on src/main/java/roomescape/controller/ReservationController.java
> +
id를 새로 부여하는 메서드인 것 같은데 DB를 사용하고 index의 개념을 생각한다면 없어도 될 것 같아요!

2024-02-04 02:57 UTC, juntae6942 commented on src/main/java/roomescape/domain/Reservation.java
> +    private String name;
long의 자료형은 wrapper로 쓰면 좋을 것 같아요

2024-02-04 02:57 UTC, juntae6942 commented on src/main/java/roomescape/domain/Reservation.java
> +
자바에 존재하는 LocalDate와 LocalTime도 알아보면 좋을 것 같아요

2024-02-04 11:38 UTC, sans29374 reviewed
코드 잘 짜신 것 같아요..!! 전반적으로 제 코드랑 비슷한 점이 많이 보여서 차이점을 찾는 것이 흥미로웠습니다. :) 자세한 리뷰는 코드에 올려두었습니다...!

2024-02-04 11:38 UTC, sans29374 commented on src/main/java/roomescape/controller/ReservationController.java
> +}
클라이언트가 오류의 원인을 쉽게 알 수 있도록 오류 메시지도 간단하게 처리해 보시는 것이 어떨까요...?!

2024-02-04 11:38 UTC, sans29374 commented on src/main/java/roomescape/controller/ReservationController.java
> +}
++) 저는 ControllerAdvice를 활용하여 예외를 처리했는데, 보배님은 ExceptionHandler를 사용하셨군요...! 둘의 차이점에서 오는 특징들도 궁금해지네요... :)

2024-02-04 11:38 UTC, sans29374 commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
예약이 삭제될 때마다 ID가 업데이트가 되는 방향이군요...! 이렇게 되면 나중에 다양한 요청이 들어왔을 때 아이디가 겹치게 되는 문제가 발생할 수도 있을 것 같아요..!

2024-02-04 11:38 UTC, sans29374 commented on src/main/java/roomescape/controller/ReservationController.java
> +@Controller
저도 Controller의 어노테이션을 @Controller로 설정했는데, @RestController로 설정하면 각 메서드에 @ResponseBody를 붙일 필요가 없어진다고 하네요...!

2024-02-04 11:38 UTC, sans29374 commented on src/main/java/roomescape/controller/ReservationController.java
> +    private final AtomicLong index = new AtomicLong(1);
저는 그냥 AtomicLong의 인스턴스를 비워두어서 0으로 시작하게 했는데, 예약 시스템 특성상 이렇게 시작점을 1로 두는 것이 더 낫겠네요...!

2024-02-04 11:59 UTC, juntae6942 commented on src/main/java/roomescape/controller/ReservationController.java
> +
저도 수정해보려고 하거든요!

2024-02-04 20:05 UTC, Kimbobae1 commented on src/main/java/roomescape/controller/ReservationController.java
> +
알아보니 스프링부트가 src/main/resources/templates 경로 내에 있는 index.html 을 welcome page로 인식하네요.
home.html 파일의 이름을 index.html로 수정하니 해당 코드가 없어도 됩니다.👍👍

2024-02-04 20:06 UTC, Kimbobae1 commented on src/main/java/roomescape/controller/ReservationController.java
> +
앗 그렇네요, 해당 메서드 제거했습니다😄

2024-02-04 20:08 UTC, Kimbobae1 commented on src/main/java/roomescape/domain/Reservation.java
> +    private String name;
long의 wrapper 클래스인 Long으로 수정하였습니다..!

2024-02-04 20:10 UTC, Kimbobae1 commented on src/main/java/roomescape/domain/Reservation.java
> +
LocalDate와 LocalTime가 있었네요..! 수정했습니다 👍

2024-02-04 20:11 UTC, Kimbobae1 commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
해당 메서드를 삭제해보았습니다..!

2024-02-04 20:11 UTC, Kimbobae1 commented on src/main/java/roomescape/controller/ReservationController.java
> +@Controller
그런 어노테이션도 있었네요..! 수정했습니다

2024-02-04 20:28 UTC, Kimbobae1 commented on src/main/java/roomescape/controller/ReservationController.java
> +}
오류메세지를 전달하도록 코드를 수정해보았습니다.
ControllerAdvice를 활용한 예외처리에 대해서는 좀더 찾아보겠습니다..!

2024-02-08 01:00 UTC, sans29374 approved these changes
수고하셨습니다...!!! 👍👍 다양한 어노테이션들을 통해 코드가 더욱 간결해진 것 같아 보기 좋습니다. :)

2024-02-08 01:26 UTC, merged